README.md
db/migrate/20190124182020_add_trackable_columns_to_user.rb
db/schema.rb

These columns are required when logging in via shib or local dev. Also updates readme to specify about database_auth environment variable.

Adds trackable columns to users table

---

Gemfile
Gemfile.lock
app/models/ability.rb
app/models/user.rb
config/role_map.yml
config/routes.rb
db/migrate/20190124224346_user_roles.rb
db/migrate/20190126002457_remove_email_index_from_users.rb
db/schema.rb
db/seeds.rb
lib/admin_setup.rb
spec/factories/users.rb
spec/features/admin_dashboard_spec.rb
spec/fixtures/config/role_map.yml
spec/lib/admin_setup_spec.rb

Adds the hydra-role-management gem to create roles for users;
Adds solution to create user admins from role_map.yml file on dev (via seeds);
Removes unique constraint and index from users.email since we are using `uid` for authentication;
Creates user admin factory and adds initial tests for admin dashboard
Closes #44 
Connected to #36 
Roles can be found at `/roles` (accessible by admins):
Select `role` to add users (accessible by admins):

Admin group

---

config/deploy.rb

This commit reworks the deploy.rb file, it should be cleaner with less lines and it adds a new linked directory which will house our admins.yml file

Change configuration of deploy.rb for admins.yml 

---

Gemfile
Gemfile.lock
app/models/curate_generic_work.rb
spec/models/curate_generic_work_spec.rb

This commit adds first 10 descriptive metadata properties. Also adds `rspec-its` gem.
Closes #85

Adds descriptive metadata

---

app/forms/hyrax/curate_generic_work_form.rb
app/models/curate_generic_work.rb
spec/features/create_curate_generic_work_spec.rb
spec/forms/hyrax/curate_generic_work_form_spec.rb
spec/models/curate_generic_work_spec.rb

1. This commit adds 10 more (10-20) descriptive metadata.
2. Comments out inclusion of Hyrax's Basic metadata - We may not need all of the basic and core metadata. Commenting out the inclusion will allow us to define our required basic and core metadata.
3. Adds `publisher` and `date_created` from basic metadata to forms.
4. Edits `create_curate_generic_work_spec` to match available metadata properties - since we do not have basic and core metadata available, we will need to write tests with our set of metadata instead of tests with default metadata properties.
Closes #86

Adds descriptive metadata part 2

---

app/indexers/curate_generic_work_indexer.rb
app/models/curate_generic_work.rb
spec/models/curate_generic_work_spec.rb

Removes the concern from our generic work type, and stops trying to index those terms.

Removes Hyrax's basic metadata

---

spec/factories/curate_generic_works.rb
spec/factories/file_sets.rb
spec/factories/users.rb

Rubocop complains that the current factories use static traits, which will be removed in a upcoming version of FactoryBot. This changes them to be dynamic, and removes those warnings.

Makes factory traits dynamic

---

.rubocop.yml
Gemfile
Gemfile.lock
app/models/user.rb
lib/admin_setup.rb

- Push Rubocop to use Ruby 2.5 syntax. This pushes the admins task, and turning off the frozen string literal changes.
- Enable the ABC Size metric, and limit the others that are still off to only the failing files.
- The User model had two problems. First, the ABC size was too high, and second, AR's #first_or_create method has been silently unsupported. Switching to #find_or_initialize_by solves the second problem, and
using #assign_attributes fixes the first.
- Pry can do debugging like byebug, but adds a bunch of convenience. Use `binding.pry` where you would have used `byebug`.

Updates Rubocop and adds Pry for debugging.

---

app/forms/hyrax/curate_generic_work_form.rb
app/views/records/edit_fields/_data_classification.html.erb
app/views/records/edit_fields/_subject_geo.html.erb
config/authorities/data_classification.yml
spec/features/create_curate_generic_work_spec.rb

Visibility and a few other params were getting escaped and being listed as unpermitted when saving form.
This commit also edits data_classification and subject_geo metadata properties to align them with the given requirements.
Closes #202

Adds visibility and other params to permitted_params for form

---

app/models/user.rb
spec/models/user_spec.rb

Before, a RecordNotFound error was raised and not caught, leading to users getting an error page instead of redirecting to root. Now, the error is caught and logged, and the users should be redirected properly.

Allows invalid users to complete signin flow

---

config/locales/hyrax.en.yml

After: ![visibility](https://user-images.githubusercontent.com/638392/59209689-ea512180-8b79-11e9-81e7-53abb079f237.JPG)
Note: This changes the name in other places as well, including the terms of service.

Changes institution_name to Emory Network.

---

app/models/curate_generic_work.rb

Dates are validated with javascript before the form is saved. In order to preserve EDTF dates, they should not be cast to the Ruby date type.

Fix date validation

---

app/models/curate_generic_work.rb

Moves to a dummy predicate, http://metadata.emory.edu/vocab/cor-terms#dataCollectionDates

Changes the predicate for Data Collection Dates to avoid a conflict.

---

config/initializers/hyrax.rb

WARN -- : Cannot enable realtime notifications atop Passenger + Apache.
Coercing `Hyrax.config.realtime_notifications` to `false`. Set this
value to `false` in config/initializers/hyrax.rb to stop seeing this
warning.

Fixes a warning from the Passenger logs

---

app/models/auth_config.rb
config/deploy/qa.rb

@rotated8 Would it be okay if we use database authentication on our systems instead of getting shibboleth set up? It would let us get to the building of the importer much more quickly.

Database auth in production

---

config/deploy.rb

Running a cap deploy should always include running database migrations;
Otherwise, we could get into a state where the database schema
and the software do not align.
I do not know what this line was trying to do:
`Rake::Task["migrate"].clear_actions`
But removing it restores the expected db:migrate task during a cap
deploy:
```
bess@paz: (master):~/projects/dlp-curate$ cap qa deploy | grep migrate
00:42 deploy:migrate
[deploy:migrate] Run `rake db:migrate`
01 bundle exec rake db:migrate
```
Connected to https://github.com/curationexperts/dlp-curate/issues/21

Database migrations should always run on cap deploy

---

app/models/file_set.rb
spec/models/file_set_spec.rb

The `original_file` property is empty when creating
a Work through the UI. This needs to be set
because it used to create file metadata and derivatives.

Original file fix

---

app/forms/hyrax/forms/collection_form.rb
app/indexers/curate_collection_indexer.rb
app/indexers/curate_indexer.rb
app/models/collection.rb
spec/rails_helper.rb
spec/support/capybara.rb
spec/system/create_collection_spec.rb

This changes the indexers for the `Collection` model
to match the chosen terms.
This is tested with a system spec that creates a `Collection`
in the UI and checks to see if it was successful. Without
these indexer changes the process will fail because it will
try to index terms that don't exist on the `Collection` model.

Change Collection Indexer to match new terms

---

spec/system/create_collection_spec.rb

Before we create a collection, ensure default admin set and permission
template exist. Otherwise, we get intermittent test failures for this
one.
Connected to https://github.com/curationexperts/in-house/issues/194

Ensure default admin set exists

---

app/importers/curate_mapper.rb
spec/importers/curate_mapper_spec.rb
spec/system/import_langmuir_from_csv_spec.rb

* Expect the csv to contain a content type string
* Match that string to a label in the appropriate QA authority
* Record the URI on the record
Connected to https://github.com/curationexperts/in-house/issues/190

Import content_type as a uri

---

spec/system/importer_guide_spec.rb

This spec is passing when you make a PR, but failing on the master branch. When failing on the master branch it looks like the page has a different title. Since this spec is about whether or not you can visit the page and not specifically about the title of the page I just changed the spec to work with both.

Fix for spec passing on PR, but failing on master

---

config/authorities/administrative_unit.yml
spec/factories/object_id.rb
spec/factories/permission_template_accesses.rb
spec/factories/permission_templates.rb
spec/models/qa/local_authority_spec.rb
spec/system/edit_collection_spec.rb

This fixes a bug where the collection edit form would not render if
there was a saved value in the administrative_unit field. The root cause
of this was that the form wanted to filter on "active" QA values, and
administrative_unit didn't have anything explicitly marked as "active".
This PR adds explicit "active" designation to the administrative_unit QA
config.
It also adds a system spec for the collection edit form as well as some
unit tests for QA configuration.
Connected to https://github.com/emory-libraries/dlp-curate/issues/418

Bug fix: key not found: "active"

---

.circleci/config.yml

The orb release being referenced wasn't a valid release number according to https://circleci.com/orbs/registry/orb/samvera/circleci-orb.  Trying the latest samvera/circleci-orb version to see if it fixes coveralls notifications.

Update CircleCI to use latest Samvera orb

---

app/models/curate/collection_type.rb
spec/models/curate/curate_collection_type_spec.rb
spec/models/hyrax/collection_type_spec.rb

Add thorough unit tests for collection type before we start making
changes, to ensure we don't break any base functionality.
Connected to https://github.com/emory-libraries/dlp-curate/issues/402

Happy path tests for collection type

---

app/models/curate/collection_type.rb
config/deploy.rb
lib/tasks/curate_collection_type.rake
spec/models/curate/curate_collection_type_spec.rb

* Create it easily with an idempotent rake task
* Run this task whenever we deploy, so we always have the expected collection type to work with
Connected to https://github.com/emory-libraries/dlp-curate/issues/383

Ensure library collection type exists on all curate systems

---

config/initializers/hyrax.rb

This adds the basic UV config to turn it on
and have it display images in developement
mode. If the `IIIF_SERVER_URL` is not set
it will use `Riiif` to display the images.
When Cantaloupe is setup that variable should
be set.

Add UV config

---

.rubocop.yml
app/importers/curate_collection_importer.rb
config/collection_metadata/langmuir_collection.csv
config/deploy.rb
lib/tasks/curate_collections.rake
spec/fixtures/csv_import/collections/langmuir_collection.csv
spec/importers/curate_collection_importer_spec.rb

* Ensure only one collection per call number is created
* If a collection object exists already, find it and update its metadata
* Run the collection creation script on deploy so we always have the
expected collections in every environment
Connected to https://github.com/emory-libraries/dlp-curate/issues/403

Create Langmuir collection on every system

---

app/forms/hyrax/forms/collection_form.rb
app/models/collection.rb
app/views/collections/edit_fields/_related_material.html.erb
spec/factories/collections.rb
spec/features/create_collection_spec.rb
spec/forms/hyrax/forms/collection_form_spec.rb
spec/models/collection_spec.rb

Collections should have a finding_aid_link field instead of a
related_material field.
Connected to https://github.com/emory-libraries/dlp-curate/issues/450

Adjust fieldname for Collections metadata

---

app/importers/curate_collection_importer.rb
spec/system/migration_collections_spec.rb

Ensure auto-created migration collections allow Repository
Administrators to deposit into them.
Connected to https://github.com/emory-libraries/dlp-curate/issues/469

Ensure migration collections have expected permissions

---

app/forms/hyrax/forms/collection_form.rb
spec/forms/hyrax/forms/collection_form_spec.rb
spec/system/create_collection_spec.rb

Remove Primary Repository ID (label=Persistent URL) from the collection
edit form.
Connected to https://github.com/emory-libraries/dlp-curate/issues/406

Remove Primary Repository ID from collection form

---

app/importers/curate_mapper.rb
spec/importers/curate_mapper_spec.rb

Earlier versions of the Langmuir csv had content_type as a string. Now
we are shifting expectations to a URI. Leave the option to provide a
string in place in case it's needed later.
Connected to https://github.com/curationexperts/in-house/issues/213

content_type can be a string or a URI

---

app/importers/collection_permission_ensurer.rb
app/importers/curate_collection_importer.rb
spec/importers/collection_permission_ensurer_spec.rb
spec/system/migration_collections_spec.rb

Manage permissions are being set, but deposit permissions
also need to be set so that admins can add to collections
from the UI. As written the UI only checks for the deposit
permission.
See: https://github.com/samvera/hyrax/blob/659e34356bace5e75358ad85b843d16b48771147/app/controllers/hyrax/my/works_controller.rb#L23

Ensure deposit permissions are set for the collection

---

app/importers/curate_mapper.rb
spec/importers/curate_mapper_spec.rb

I'm guessing that "Emory Network" should map to "authenticated".
We should double-check this with Emily, but I think this should be good
enough to allow us to start iterating on the metadata import.
Connected to https://github.com/curationexperts/in-house/issues/213

Update visibility mapping

---

Gemfile
Gemfile.lock
app/controllers/metadata_details_controller.rb
app/lib/curate_generic_work_attributes.rb
app/lib/metadata_details.rb
app/views/metadata_details/show.html.erb
config/routes.rb
spec/controllers/metadata_details_spec.rb
spec/lib/metadata_details_spec.rb
spec/system/importer_guide_spec.rb

This adds a class that assembles a `Hash` containing
information about the metadata in the application and
displays it as the field guide in the importer.
The information included in the hash is the attribute name,
the RDF predicate, the label used in the form, validation used
in the model, the type of the value, and whether or not
the field is singular or multiple.

Auto-generate metadata guide

---

Gemfile
Gemfile.lock
spec/lib/admin_setup_spec.rb
spec/rails_helper.rb
spec/system/create_collection_spec.rb
spec/system/show_collection_spec.rb

* Remove database_cleaner: now that we've switched to system specs it's no longer needed
* Upgrade capybara to address deprecation warnings in tests
Connected to https://github.com/curationexperts/in-house/issues/222
Connected to https://github.com/curationexperts/in-house/issues/196

Selenium deprecations

---

app/importers/curate_mapper.rb
app/uploaders/zizia/csv_manifest_validator.rb
spec/support/capybara.rb

* Use Zizia config to determine what Mapper class to use
* Look at that mapper class and get the allowed headers instead of
maintaining a separate list of valid headers
* Set newly required config for webdrivers
Connected to https://github.com/curationexperts/in-house/issues/229

Get valid CSV headers directly from CurateMapper

---

app/importers/curate_mapper.rb
app/lib/metadata_details.rb
app/views/metadata_details/show.html.erb
spec/lib/metadata_details_spec.rb

For each field, look up its corresponding import header in the
configured Zizia mapper class.
Connected to https://github.com/curationexperts/in-house/issues/226

Add Import header to metadata guide

---

app/assets/stylesheets/curate.scss
app/helpers/metadata_details_helper.rb
app/views/metadata_details/show.html.erb

Make it easier to find missing import headers and form labels by putting
the missing data indicators in a different color.
Connected to https://github.com/curationexperts/in-house/issues/226

Style missing data on the metadata field guide

---

app/controllers/metadata_details_controller.rb
app/lib/metadata_details.rb
app/views/metadata_details/show.html.erb
config/routes.rb
spec/controllers/metadata_details_spec.rb
spec/lib/metadata_details_spec.rb

This provides a link to a CSV representation
of the information displayed in the guide.

Add a downloadable CSV to the metadata guide

---

Gemfile
Gemfile.lock
app/importers/modular_importer.rb
app/logging/log_formatter.rb
config/application.rb
config/environment.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/zizia.rb

Before we do these long migrations, let's get the logging system cleaned up so we'll easily be able to measure performance metrics and track import jobs.
* Upgrade to zizia 3.x, which uses the Rails logger instead of a custom logging solution
* Format the dlp-curate Rails logger so it includes a timestamp
* Turn logging level down to INFO for a better signal-to-noise ratio
Connected to https://github.com/curationexperts/dlp-curate/issues/16

Improve logging 

---

.fcrepo_wrapper
.solr_wrapper
.solr_wrapper.yml
config/fcrepo_wrapper_test.yml
config/solr_wrapper_test.yml

* Use fedora 4.7.5 to match production
* Remove redundant solr config file to reduce confusion
* Add download_dir directive so we don't have to re-download over and
over again when our local rails tmp directory gets blown away

Standardize local fedora and solr

---

app/lib/metadata_details.rb
app/views/metadata_details/show.html.erb
spec/controllers/metadata_details_spec.rb
spec/lib/metadata_details_spec.rb

Removes one level of structure from metadata details.
Refactors tests correspondingly.

Refactor MetadataDetails to simplify object structure

---

app/controllers/metadata_details_controller.rb
spec/controllers/metadata_details_spec.rb

Adds support for requests to /importer_documentation/guide.json.
Redirects any unrecognized request formats to .html

Handle JSON format requests for metadata_details

---

app/actors/hyrax/actors/file_set_actor.rb
app/importers/file_arranger.rb
spec/factories/file_sets.rb
spec/importers/file_arranger_spec.rb

This adds a FileArranger that is used to order the
Langmuir files correctly. If the FileSet is labeled
'Front' it will be first in ordered_members and if
it is labeled 'Back' it will be second unless there
is only a 'Back'.
In the future this class should altered so that
it arranges the files based on the index in the filename.
Connected to curationexperts/in-house#269

Ordering for Langmuir imports

---

.rubocop.yml
app/views/hyrax/base/_form_visibility_component.html.erb
config/initializers/access_right.rb
config/initializers/permission_badge.rb
config/initializers/visibility.rb
config/locales/hyrax.en.yml
spec/system/create_curate_generic_work_spec.rb

This allows you to choose additional
visibilty levels that are synonomous
with private.
On the edit form these will be labeled
with the new name and you can programmatically
create them.
On the show view these will display as private. In
the future, the show view should reflect the actual
granularity we want the permission levels to have.
Connected to curationexperts/in-house#274

Add custom visibility levels

---

app/views/hyrax/base/_form_visibility_component.html.erb

These need to refer to the strings/keys in the `AccessRight`
classes.

Fix visibility on form

---

app/importers/curate_mapper.rb
spec/system/import_langmuir_from_csv_spec.rb

Add expected headers to the allowed_headers method so they do not raise
warnings.
Connected to https://github.com/curationexperts/in-house/issues/401

Do not raise warnings for expected headers

---

app/importers/curate_mapper.rb
spec/importers/curate_mapper_spec.rb

Refactors the `CurateMapper#singular_fields` method to dynamically generate the list.  This eliminates the need to keep the mapper and the model in sync manually in this way.
As a side effect, a number of previously missing singular fields will be available if new fields are added to the mapper:
```
["administrative_unit", "arkivo_checksum", "author_notes", "conference_dates", "content_type",  
"date_modified", "date_uploaded", "depositor", "geographic_unit", "isbn", "issn", "issue",  
"on_behalf_of", "owner", "page_range_end", "page_range_start", "parent_title",  
"primary_repository_ID", "proxy_depositor", "publisher_version", "re_use_license",  
"rights_documentation", "scheduled_rights_review", "scheduled_rights_review_note", "sponsor",  
"state", "technical_note", "volume"]
```

Dynamically generate a list of singular fields used by the import mapper

---

app/views/hyrax/dashboard/sidebar/_tasks.html.erb
spec/system/admin_dashboard_spec.rb

This changes the sidebar so that it only shows
the import CSV link to admin users.
Connected to curationexperts/in-house#414

Only show importer link to admins

---

app/importers/curate_collection_importer.rb
spec/fixtures/csv_import/collections/collections.csv
spec/importers/curate_collection_importer_spec.rb

Because `local_call_number` is an optional field on collections, a designated `deduplication_key` is now used to prevent collections from being imported more than once from a CSV. Changes made to collection metadata in the UI will persist when an attempt is made to re-import the collection.
Resolves: #665

Use deduplication key for CSV collection imports

---

.rubocop.yml
config/initializers/characterization_service.rb
spec/services/characterization_service_spec.rb

* Modifies the checksum generation method in the characterization
service. Finds the file_set using the object (file) ID, and
then passes the file_set object along with the event hash,
to the create_preservation_event method in the PreservationEvents
module.
* Adds spec which tests the preservation_event is saved on the
file_set and tests expectations for preservation_event values.

Adds preservation_event for message digest calculation

---

app/controllers/hyrax/file_sets_controller.rb
app/forms/curate/forms/file_set_edit_form.rb
app/views/hyrax/file_sets/_form.html.erb
config/locales/hyrax.en.yml
spec/forms/curate/forms/file_set_edit_form_spec.rb
spec/system/edit_file_spec.rb

* This commit changes the form_class for FileSet form
to now use our new form_class, Curate::Forms::FileSetEditForm
which inherits the Hyrax::Forms::FileSetEditForm class, therefore,
we get everything from the hyrax class but we also add our own terms
for Curate in the Curate::Forms::FileSetEditForm class.
* Also, removes existing spec for Hyrax's fileset edit form and
replaces an identical spec for Curate's fileset edit form with new
terms.
* Edits the edit_file system spec to make sure the FileSet use
category can actually be edited from the FileSet edit page.

Adds FileSet use category edit field to FileSetEditForm

---

app/views/hyrax/file_sets/media_display/_image.html.erb
app/views/hyrax/file_sets/media_display/_office_document.html.erb 
app/views/hyrax/file_sets/media_display/_pdf.html.erb 

Restores the original Download functionality from the View FileSet page, so that the link says "Download" and the link to download points to the Preservation Master File (not to one of the additional files).
Closes #684

changes links to preservation master file

---

app/importers/langmuir_preprocessor.rb
spec/importers/langmuir_preprocessor_spec.rb

The location of Langmuir files cannot be predicted with complete
reliablity, so we need to retain the relative path information
in order to locate the files on the new EFS mount point.

Save Langmuir filenames with relative paths

---

app/importers/modular_importer.rb
spec/system/importer_preprocessed_langmuir_spec.rb

Before this commit `PreIngestWork`s were being created for
every row in the CSV. This adds logic to only create the
`PreIngestWork` for rows that have the value `work` in the
`type` column. `PreIngestFile`s are then attached to the
correct `PreIngestWork` based on the `deduplication_key`.
After this commit the batch status page will be correctly
grouped.

Create PreIngestWorks only for rows with the correct type

---

Gemfile
Gemfile.lock
spec/jobs/create_work_job_spec.rb
spec/system/import_langmuir_from_csv_spec.rb
spec/system/langmuir_file_attachment_spec.rb
spec/system/rights_statements_spec.rb

Includes these changes:
- Toggle files table [\#63](https://github.com/curationexperts/zizia/pull/63) ([little9](https://github.com/little9))
- Paginate PreIngestWorks [\#62](https://github.com/curationexperts/zizia/pull/62) ([little9](https://github.com/little9))
- Change count language on preview screen [\#61](https://github.com/curationexperts/zizia/pull/61) ([little9](https://github.com/little9))

Update Zizia to v5.3.0

---

app/jobs/characterize_job.rb

The event hash for characterization preservation events now includes the FITS software version as well as revised details.
Resolves: #737

Revise characterization preservation events

---

app/importers/yellowback_preprocessor.rb
spec/importers/yellowback_preprocessor_file_spec.rb
spec/importers/yellowback_preprocessor_metadata_spec.rb

Use the emory_ark as the deduplication key for yellowbacks since the other
fields likely to be unique like the MMSID can be duplicated when more than
one copy of the same yellowback volume exists. The ARK is the only ID that
is unique for each copy of yellowback.  See "The common moths of England" in
the test fixture for an example.

Provide a deduplication_key for yellowback manifests

---

app/views/hyrax/base/_form_visibility_component.html.erb
config/initializers/prepends.rb
config/locales/hyrax.en.yml
config/prepends/custom_permission_badge.rb
spec/system/create_curate_generic_work_spec.rb

Update visibility badges to match specifications from Curate user group
Connected to https://github.com/curationexperts/in-house/issues/448

Update visibility badges to match Emory expectations

---

app/importers/yellowback_preprocessor.rb
spec/importers/yellowback_preprocessor_metadata_spec.rb

Curate uses `content_genres` and `contributors` in its metadata
model.
Connected to https://github.com/curationexperts/in-house/issues/464
Connected to https://github.com/curationexperts/in-house/issues/465

Change genre and contributor in Yellowback preprocessor

---

lib/tasks/curate_kirtas.rake

Yellowbacks and some yearbooks were digitized using Kirtas (https://www.kirtas.com)
equipment and share a common directory structure.  This PR provides a task
`rake curate:kirtas` that can be invoked to process pull list and MARC records from
the command line.
**Kirtas preprocessor**
```
USAGE:
rake curate:kirtas csv=pull_list.csv xml=alma.xml
RETURNS:
pull-list-merged.csv in the samve folder as pull-list.csv
```

Add a rake task to pre-process yellowbacks

---

Gemfile
Gemfile.lock
config/deploy/cd.rb
config/deploy/qa.rb

Emory does not appear to be using systemd and dce is on our servers,
so we need to supply some additional parameters to the stage file to
let sidekiq know how to restart appropriately.
For more details see:
https://github.com/seuros/capistrano-sidekiq#integration-with-systemd
NOTE: the PR explicitly sets the service name to be backwards compatible with the name created by the DCE sidekiq ansible role.  By default the capistrano-sidekiq gem now adds the state name as a suffix, we may want to move to the default configuration in the future, but I wanted to stay backward compatible in case we have any monitoring set up for the old service name.

Update Capistrano stages to use systemd for sidekiq

---

app/importers/modular_importer.rb

This changes the `modular_importer` so that it reusues
existing `PreIngest` objects instead of creating new ones.
Connected to https://github.com/curationexperts/in-house/issues/447

Don't create duplicate PreIngest objects

---

app/actors/hyrax/actors/curate_generic_work_actor.rb
spec/actors/hyrax/actors/curate_generic_work_actor_spec.rb

* This commit removes the metadata_extraction event for the time being.
* Also, event hashes are now created after save.
* It adds visibility of the curation_concern to policy_assignment
event_details.
* Edits the spec to match revised work events.

Edits work creation preservation_events

---

.rubocop.yml
app/actors/hyrax/actors/file_set_actor.rb
config/initializers/job_io_wrapper.rb
spec/actors/hyrax/actors/file_set_actor_spec.rb
spec/models/job_io_wrapper_spec.rb

* This commit removes the replication event from the file_set_actor
since we are no longer logging when the file_set saves.
* We are now creating an event on file ingest in the job_io_wrapper
model. We look for what is returned from the file_actor.ingest_file
method. If `false` is returned and the file is not attached to the file_set,
we create a failure event, else a success event.
Notes:
* ingest_file method in the JobIoWrapper method is modified. We save the response
from the `file_actor.ingest_file` method call. If false is returned from L#16 in
`config/intializers/file_actor.rb` then a failure event is created, else success
event.
Output in fedora:
For success event (on fileset):
For failure event (on fileset):

Revises where file_replication/submission event happens

---

app/importers/modular_importer.rb

This changes the query that clears out `PreIngestFiles` during
a retry so that it uses only one call.

Change PreIngestFile deletion query

---

app/importers/langmuir_preprocessor.rb
spec/importers/langmuir_preprocessor_spec.rb

Even though the metadata fields in a fileset rows aren't read, we
still want them to be the same length as metadata rows.  This makes
checking row length easy, so we can ensure manually edited manifest
files don't have quotation or line break errors.

Ensure processed Langmuir rows have the expected length

---

.rubocop.yml
app/lib/metadata_definitions.rb
app/lib/metadata_details.rb
config/zizia/usage.yml
spec/controllers/metadata_details_spec.rb

This adds `visibility` to the guide and includes the
availble options in the the `usage.yml` file.
Connected to https://github.com/curationexperts/in-house/issues/484

Add visibility to guide

---

.circleci/config.yml

When a system test fails, capybara will take a screenshot of the failure. When this happens in Circle, this PR uploads them as artifacts. As an example, see the two screenshots from a failed run of this PR: https://app.circleci.com/jobs/github/emory-libraries/dlp-curate/5142/artifacts

Capture the screenshots Circle creates for system test failures

---

Capfile
config/deploy/arch.rb
config/deploy/production.rb
config/deploy/test.rb
config/honeybadger.yml

Deploys to arch, test, and prod will report their environment as such, rather than all saying "production"

Adds Honeybadger

---

spec/models/job_io_wrapper_spec.rb

This commit adds preferred file arg to create_with_varied_file_handling
method since this a required arg with no default. The job_io_wrapper_spec
was failing because of the missing arg.

Adds preferred file arg to job_io_wrapper_spec

---

.gitignore
app/lib/iiif_url_builder_service.rb
config/initializers/hyrax.rb
spec/lib/iiif_url_builder_service_spec.rb

This changes the IIIF image builder lambda
so that it uses a seperate service to generate
the URL based on the sha1 stored in solr. The new
URL is used if the server has the `FEDORA_ADAPTER` env
variable set to 's3', otherwise it will generate the URLs
based on the `FileSet` id.
Connected to emory-libraries/dlp-lux#61

Generate IIIF image urls based on sha1

---

spec/system/import_langmuir_from_csv_spec.rb
spec/system/langmuir_file_attachment_spec.rb
spec/system/viewing_a_work_spec.rb

Temporarily stops running part of a test that almost always creates a Net::ReadTimeout Error.

Comments out test giving timeout errors.

---

spec/fixtures/csv_import/yellowbacks/yellowbacks_marc.xml
spec/importers/yellowback_preprocessor_metadata_spec.rb

Emory has decided to remove subfield 5 (institution) from contributor
(field 700) entries.  This PR updates the fixtures to match the live
data going forward.

Update MARC fixture to match sample data

---

app/controllers/hyrax/fixity_checks_controller.rb
app/views/hyrax/file_sets/show.html.erb
spec/controllers/hyrax/fixity_checks_controller_spec.rb
spec/system/show_file_spec.rb

* This commit adds a button for running fixity check on demand.
* We modify the create method in the FixityChecksController since
we no longer need to render json, but redirect to the file_set show
page with the result from the fixity check.

adds fixity check button on file_set show page

---

app/jobs/fixity_check_job.rb
spec/jobs/fixity_check_job_spec.rb

* Adds fixity_check preservation_event to run_check method in
FixityCheckJob. Takes the ChecksumAuditLog for a file and checks
for the `passed` attribute. If true, creates success event else
failure event.

Adds fixity_check preservation_event

---

app/indexers/curate_generic_work_indexer.rb
app/models/curate_generic_work.rb
app/models/solr_document.rb
app/services/licenses_label_service.rb
spec/factories/curate_generic_works.rb
spec/models/curate_generic_work_spec.rb

* In order to support required metadata display in Lux, `:rights_statement` and `:re_use_license` now have human-readable versions indexed in the Solr document on the Curate side. The `LicensesLabelService` is created to support human-readable versions of `:re_use_license`.
* `:grant_information` and `:issue` are now indexed as `:stored_searchable` in order to be made available for Lux.

Index human-readable metadata fields for Lux

---

app/jobs/fixity_check_job.rb
lib/tasks/fixity_check.rake
spec/jobs/fixity_check_job_spec.rb

* We are adding a new rake task to run fixity_check on all file_sets.
Max days between check has been set to 90. We are checking for all
versions of a file for all files in a given file_set. Also, a logger
output has been added.

Adds fixity_check rake task

---

.rubocop.yml
app/actors/hyrax/actors/file_set_actor.rb
app/controllers/hyrax/file_sets_controller.rb
spec/actors/hyrax/actors/file_actor_spec.rb
spec/actors/hyrax/actors/file_set_actor_spec.rb
spec/controllers/hyrax/file_sets_controller_spec.rb
spec/fixtures/hyrax_generic_stub.txt
spec/rails_helper.rb
spec/support/response_matchers.rb

* We are adding the required `preferred` arg to the update_content method
in FileSetActor.
* Also, updating default relation to pmf in FileSetActor.
* FileSetController and FileSetActor specs are copied over from hyrax and
adjusted to our requirements.
* `main_app` definition is added to the rails_helper.

Adds preferred keyword when updating file_set

---

spec/controllers/hyrax/file_sets_controller_spec.rb

* We are skipping tests for versioning of files for now, due to its flakey
behavior. Will come back to it when working on versioning of files.

Skip file versions tests

---

app/services/date_service.rb
spec/services/date_service_spec.rb

- Dates with only month and year and uncertain dates ending in "~" are now made human-readable for Lux
- See [Lux issue 177](https://github.com/emory-libraries/dlp-lux/issues/177)

Humanize additional date formats for Lux

---

app/indexers/curate_generic_work_indexer.rb
app/models/solr_document.rb
spec/indexers/curate_generic_work_spec.rb
spec/models/curate_generic_work_spec.rb

The `year_for_lux` field combines and deduplicates `year_created` and `year_issued` for Lux faceting.

Add year_for_lux field to Solr document

---

app/forms/hyrax/curate_generic_work_form.rb
spec/forms/hyrax/curate_generic_work_form_spec.rb

* This commit adds the missing `ordered_member_ids` param to the list of permitted
params for the work form. This will fix the issue where we were unable to
reorder filesets for a work.
* Tests are also added for checking of permitted params and model attributes.

Adds `ordered_member_ids` to work form params

---

config/honeybadger.yml

Use Socket.gethostname rather than an ENV var, which seems to not get read reliably.

Fix Honeybadger Env

---

.rubocop.yml
app/lib/index_file_set.rb
lib/tasks/index_file_sets.rake
spec/lib/index_file_set_spec.rb

* This commit adds a way to reindex file_sets that have a missing
`mime_type` in solr and appends file_set info to csv.
* Also, adds a way to regen thumbnails for file_sets that have a
default preview image as thumbnail and appends file_set info to csv.

Adds rake task to reindex file_sets and regen thumbs

---

app/forms/hyrax/forms/collection_form.rb
spec/forms/hyrax/forms/collection_form_spec.rb

* This commit adds `thumbnail_id` to terms (params) for the collection
form which was missing earlier. We will now be able to edit the
thumbnail for a collection.

Adds `thumbnail_id` to collection_form

---

config/deploy.rb

This PR will add the tmp/csv_uploads and tmp/csv_uploads_cache to the /shared folder of the application, this should resolve any csv errors that the app has been having.

Link csv upload folders to shared

---

.rubocop.yml
app/indexers/curate_generic_work_indexer.rb
app/models/curate_generic_work.rb
app/models/solr_document.rb
spec/indexers/curate_generic_work_spec.rb

- Sortable fields for `:title` and `:creator` are indexed for Lux
- Addresses [Lux ticket 245](https://github.com/emory-libraries/dlp-lux/issues/245)

Index sort fields for Lux

---

README.md
app/builders/curate_manifest_helper.rb
app/controllers/hyrax/curate_generic_works_controller.rb
app/lib/create_manifest.rb
app/models/manifest_ability.rb
app/presenters/hyrax/curate_generic_work_presenter.rb
app/presenters/hyrax/displays_image.rb
lib/tasks/create_manifest.rake
spec/controllers/hyrax/curate_generic_works_controller_spec.rb
spec/fixtures/manifest_fixture.json
spec/lib/create_manifest_spec.rb
spec/presenters/hyrax/curate_generic_work_presenter_spec.rb

* Manifest creation for large book objects times out. This PR implements caching of manifests. If there is a cached manifest for an object, UV will use that, else it'll create a new manifest and cache it for future use.
* There is also a rake task that creates manifests for all the works (or a single work) and caches them.
Rake task: `RAILS_ENV=*env* bundle exec rails curate:works:create_manifest` OR `RAILS_ENV=*env* bundle exec rails curate:works:create_manifest work=*work_id*`

Adds manifest caching

---

app/indexers/curate_generic_work_indexer.rb
app/models/curate_generic_work.rb
app/models/solr_document.rb
spec/indexers/curate_generic_work_spec.rb

- In order for objects in Lux to be sorted case-insensitively by `:title` and `:creator`, those fields must be stored in Solr as `:title_ssort` and `:creator_ssort`, not `:title_ssi` and `:creator_ssi` as implemented in #917

Fix sortable fields for Lux

---

app/indexers/curate_generic_work_indexer.rb
app/models/solr_document.rb
spec/indexers/curate_generic_work_spec.rb

- In order to sort by date in Lux, a single-valued `:year_for_lux` field is indexed in Solr
- Date sorting will go by an object's earliest year per [Lux ticket 277](https://github.com/emory-libraries/dlp-lux/issues/277)

Index sort field for date

---

app/controllers/hyrax/file_sets_controller.rb
app/lib/index_file_set.rb
app/models/file_set.rb
spec/models/file_set_spec.rb

* This commit adds a new file_set instance method `preferred_file`
which returns the preferred_file for the file_set.
* Instances where `preferred_file` logic was being used is replaced
with a call to this new instance method.
* Tests are updated as well.

Adds preferred_file method for file_set instance

---

.env.development
.gitignore
.rubocop.yml
config/prepends/custom_visibility.rb
spec/factories/curate_generic_works.rb
spec/models/lux_visibility_spec.rb

- Registered users should see Emory Low and Emory High in Lux
- Unauthenticated users should see Public and Public Low objects in Lux
Connected to [#289 in Lux](https://github.com/emory-libraries/dlp-lux/issues/289)

Visibility for Lux

---

app/forms/hyrax/curate_generic_work_form.rb
spec/forms/hyrax/curate_generic_work_form_spec.rb

* This commit adds rendering_ids param to the param list for the
work form. Now we will be able to add rendering options for a work
through the UI and see results in UV for downloads.

Adds rendering_ids to work form

---

.rubocop.yml
app/indexers/curate_generic_work_indexer.rb
app/models/solr_document.rb
spec/models/curate_generic_work_spec.rb

- Solr documents for hierarchical objects (i.e., CurateGenericWorks with one or more CurateGenericWorks as children) now index the IDs and titles of child objects as pairs in the `:child_works_for_lux` field.

Index child metadata for hierarchical objects

---

app/controllers/iiif_controller.rb
config/routes.rb
spec/controllers/iiif_controller_spec.rb
spec/routing/iiif_routing_spec.rb

It isn't enough that the IiifController proxies image requests to
cantaloupe -- it needs to also proxy info.json requests. This PR adds
that feature.
BUGFIX: Only add an extra slash when it is needed to construct a IIIF url
Connected to https://github.com/emory-libraries/dlp-lux/issues/260

IIIF controller must proxy info.json requests

---

app/indexers/curate_generic_work_indexer.rb
spec/models/curate_generic_work_spec.rb

- `thumbnail_path` is added to `child_works_for_lux`
- Formatting of `child_works_for_lux` field is simplified for easier parsing on Lux side

Index thumbnail_path for Lux child works

---

app/controllers/iiif_controller.rb
spec/controllers/iiif_controller_spec.rb

When the Access-Control-Allow-Origin header is missing, the content sent is not loaded by UV.

Sets the CORS header for the IIIF proxy

---

app/controllers/hyrax/file_sets_controller.rb

* This commit removes preferred keyword from update_content method call
in file_sets_controller. The preferred file symbol is being received as a
normal arg in file_set_actor's update_content method and we were previously
passing this a hashed key-value pair argument from the file_sets_controller update 
method. By removing the key `preferred:` from the file_sets_controller, we pass this
as a normal argument instead of the requirement of a keyword.

Removes keyword arg from update_content

---

app/indexers/curate_collection_indexer.rb
app/indexers/curate_generic_work_indexer.rb
spec/models/collection_spec.rb
spec/models/curate_generic_work_spec.rb

- Fields are indexed in Solr for (1) the number of works in a collection and (2) the id and title of a child work's parent work
- See [Lux ticket 280](https://github.com/emory-libraries/dlp-lux/issues/280)

Index fields for Lux search results display

---

.rubocop.yml
app/jobs/check_binaries_job.rb
lib/tasks/check_binaries.rake
spec/jobs/check_binaries_job_spec.rb

* This commit adds a job that will take a bucket as input and check that
files in file_sets exist in s3 or not.
* There is a rake task that kicks off this job: `RAILS_ENV=*env* bundle
exec rails curate:file_sets:check_binaries bucket=*s3-bucket-name*
file_set=*optional*`

Adds a job to check if binaries exist in s3

---

app/presenters/hyrax/displays_image.rb
spec/presenters/hyrax/file_set_presenter_spec.rb

Closes #681 
After multiple attempts writing system tests for iframe for iiif there is no way to identify which file it is displaying within the UI. Iframe point directly to the work manifest. The image is drawn with Canvas.
Hyrax only has tests for display_image in a file_set_presenter_spec.rb. This would be for a different ticket where we need to display preferred image on a fille_set page with UV

displays preferred image in work show page iiif

---

config/initializers/active_fedora_timeout.rb
spec/unit/fedora_spec.rb

* Currently, request to create a graph for descendants in fedora times
out. In this commit, we add request options when creating a Faraday
connection. This way we can specify timeout in seconds so that the
read request for graph finishes. This is added by default in ActiveFedora
12+ and this monkey patch can be removed once we upgrade AF. Refer:
https://github.com/samvera/active_fedora/pull/1271
* This will solve the issue where ResolrizeJob used to timeout.

Adds request options to Faraday connection

---

app/jobs/check_binaries_job.rb
spec/jobs/check_binaries_job_spec.rb

* The csv was not being passed as an arg when running check_binaries
job on all file_sets. This missing arg is being added to the method
call and the definition. Tests are also updated for the same.

Passes missing csv arg in check_binaries

---

app/indexers/curate_collection_indexer.rb
spec/indexers/collection_indexer_spec.rb

- The sortable fields for Lux `title_ssort` and `creator_ssort` are now indexed on Collections in addition to CurateGenericWorks

Index sort fields on collections

---

app/controllers/hyrax/curate_generic_works_controller.rb
app/controllers/iiif_controller.rb
app/services/manifest_builder_service.rb
config/routes.rb
spec/controllers/hyrax/curate_generic_works_controller_spec.rb
spec/fixtures/manifest_fixture.json
spec/routing/iiif_routing_spec.rb
spec/services/manifest_builder_service_spec.rb
spec/system/iiif_manifest_spec.rb

Move the IIIF manifest generation out of CurateGenericWorksController,
where it is gated by Shibboleth, and into the iiif controller, where it
is more publicly accessible. The goal is to let us load iiif images for
public_low_view objects.
Once this is merged you should be able to get a work's manifest by visiting `/iiif/WORKID/manifest`
Connected to https://github.com/emory-libraries/dlp-lux/issues/313

Manifests should always be available

---

app/controllers/omniauth_callbacks_controller.rb
spec/controllers/omniauth_callbacks_controller_spec.rb

* In this commit, we redirect the user to omniauth request's origin
if it exists, else will redirect to the dashboard. Refer:
https://github.com/omniauth/omniauth/wiki/Saving-User-Location

Redirects to origin when signing in via shib

---

app/controllers/hyrax/curate_generic_works_controller.rb
app/controllers/iiif_controller.rb
app/presenters/hyrax/curate_generic_work_presenter.rb
app/services/manifest_builder_service.rb
config/routes.rb
spec/presenters/hyrax/curate_generic_work_presenter_spec.rb
spec/services/manifest_builder_service_spec.rb
spec/system/iiif_manifest_spec.rb

* We are changing the manifest url to `host_name/iiif/work.id/manifest`
to meet lux requirements.
* In this commit, we are also changing the way `build_manifest` gets
called. We now pass the presenter to the manifest builder class from
the works_controller so we don't need to worry about building a
presenter for the manifest builder service.
* We are also editing the iiif_controller's manifest method when it
calls the `build_manifest` method by passing a presenter that we
create in the controller itself. Here, when we create a presenter
for the work, we are passing the work's solr_doc, creating a new
ability for the `current_user`, and the request is nil. When the
request is nil, the manifest_url is being built by passing the
host manually to the polymorphic_url method.

Changes manifest_url to meet lux requirements

---

app/models/collection.rb
app/models/curate_generic_work.rb

- `contributors` and `keywords` are made facetable for Lux on both CurateGenericWorks and Collections

Index facetable fields for Lux

---

app/controllers/iiif_controller.rb
spec/controllers/iiif_controller_spec.rb

* When we load a work in lux for which a manifest isn't cached, it creates a shortened manifest. If we then delete that manifest, and load the same work in curate, the manifest is generated properly.
* Shortened manifest through lux might be because when lux calls the manifest method in the iiif_controller in curate (https://github.com/emory-libraries/dlp-curate/blob/master/app/controllers/iiif_controller.rb#L23), it creates an ability for the current_user (https://github.com/emory-libraries/dlp-curate/blob/master/app/controllers/iiif_controller.rb#L63). Since, lux might not know or pass the current_user, we get an incorrect manifest.

Changes ability for manifest creation to read all

---

app/lib/create_manifest.rb
app/services/manifest_builder_service.rb
dotenv.sample
spec/controllers/hyrax/curate_generic_works_controller_spec.rb
spec/lib/create_manifest_spec.rb
spec/presenters/hyrax/file_set_presenter_spec.rb
spec/services/manifest_builder_service_spec.rb
spec/system/iiif_manifest_spec.rb

* We are adding an env variable that will contain the path to the
directory where manifests get cached. Path example:
`full/path/to/directory/`

Adds env variable for manifest cache path

---

app/presenters/hyrax/curate_generic_work_presenter.rb
spec/controllers/iiif_controller_spec.rb
spec/presenters/hyrax/curate_generic_work_presenter_spec.rb

* In this commit, we are adding metadata to work manifests that
get generated. Only selective metadata is added to the manifest.
* This will help when viewing works in lux, and will appear in
the more information tab in UV.
Example as seen in Lux:

Adds metadata to manifest

---

app/controllers/iiif_controller.rb
spec/controllers/iiif_controller_spec.rb

Emory's cantaloupe servers are set to look up images by SHA1 checksum.
Updating the logic here to match that expectation.
Connected to https://github.com/emory-libraries/dlp-lux/issues/313

Image lookup is by SHA

---

.env.development
.gitignore
.rubocop.yml
app/controllers/iiif_controller.rb
spec/controllers/iiif_controller_spec.rb

For low_res visibility images, do not allow region values that would
enable deepest levels of zooming.
Default value is 800 pixels. This can be adjusted via an environment
variable MIN_TILE_SIZE_FOR_LOW_RES.
Connected to https://github.com/emory-libraries/dlp-lux/issues/313

 Limit deep zoom by limiting the region values

---

app/controllers/iiif_controller.rb
spec/controllers/iiif_controller_spec.rb
spec/fixtures/iiif_responses/info.json

UV was going directly to iiif-cor via the info.json, re-writing the info.json to make sure UV is only attempting to go via the Curate controller.
Note pixel height and width
Before 
After
Before on left, after on right, subject's eye. After image is more pixelated / has less information

Info json url

---

app/lib/curate_purl.rb
app/presenters/hyrax/collection_presenter.rb
app/presenters/hyrax/curate_generic_work_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/hyrax/collections/_show_descriptions.html.erb
dotenv.sample
spec/controllers/iiif_controller_spec.rb
spec/presenters/hyrax/curate_generic_work_presenter_spec.rb
spec/system/show_collection_spec.rb

* Adds the persistent url pattern to the work and collection show page in
curate and also adds this to the manfiest metadata to be displayed
in the more info tab in lux.
* Lux base_url is added through an env variable.
Curate work show page:
Lux more info tab:
Curate collection show page:

Adds persistent url to work show page and manifest

---

app/controllers/hyrax/dashboard/collections_controller_override.rb
app/controllers/hyrax/uploads_controller.rb
app/models/hyrax/uploaded_file.rb
app/views/hyrax/dashboard/collections/_form_branding.html.erb
app/views/hyrax/uploads/create.json.jbuilder
config/application.rb
db/migrate/20200312194124_add_banner_to_uploaded_files.rb
db/schema.rb
spec/controllers/hyrax/uploads_controller_spec.rb
spec/system/edit_collection_spec.rb

* This commit enables uploading a banner image for a collection and
saving it. Since we have changed the uploaded_files table provided by
hyrax, we need to add a new column to the table called `collection_banner`
that will be used to upload a file using carrierwave.
* We are also overwriting the `add_new_banner` method because we need to
reference `collection_banner_url` instead of the default provided by
hyrax.
Collection edit:
Collection show page:

Adds a way to upload banner image for a collection

---

app/controllers/iiif_controller.rb
config/deploy.rb
spec/requests/iiif_requests_spec.rb

Per Emory middleware, need to include X-Forwarded-For headers to capture user's IP address for "Rose High View" IP restrictions, rather than the Load Balancer's IP address.

X forwarded for

---

.gitignore
config/deploy.rb
config/deploy/arch.rb
config/deploy/localhost.rb
config/deploy/production.rb
config/deploy/test.rb
config/initializers/hyrax.rb

This branch will add a new optional environment variable called BRANDING_PATH, this will control where curate save banners and other branding images after the ingest process. Additionally, an optional capistrano variable called branding_symlink_path will create a symlink at public/branding to where the path is defined.

Add new env var and capistrano task to fix banner persistence

---

app/indexers/curate_collection_indexer.rb
spec/indexers/collection_indexer_spec.rb

1. curate_collection_indexer.rb: adds the custom field to the indexer with two methods that pluck
the needed path from the document object.
2. collection_indexer_spec.rb: creates the tests for the new index field.

Indexes banner path to the Solr query.

---

app/controllers/iiif_controller.rb
spec/system/iiif_access_controls_spec.rb

See issue #450 in Lux 
https://app.zenhub.com/workspaces/dlp-lux-5c75900b135e053ed882c4d0/issues/emory-libraries/dlp-lux/450

Curate users should be able to see images of any visibility

---

spec/indexers/curate/file_set_indexer_spec.rb
spec/models/curate_generic_work_spec.rb

Without cleaning, these test can sometimes fail with an LDP error.

Cleans some more specs

---

app/helpers/hyrax/iiif_helper.rb
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
app/views/manifest/manifest.json.jbuilder
public/uv-emory-config.json
spec/fixtures/manifest_output.rb

Connected to #1054 
Connected to #984 
* Current view and Whole Image Low Res options are currently not working as expected because of the hardcoded 640x480 width and height. This commit changes those fixed values to preservation master file's width and height. This should now fix the issue where the current view would sometimes show negative pixels and not download correctly. Along with this, distortion when downloading whole image low res (where height gets fixed at 750px) should also be fixed.

Delivers constrained size options in UV download dialoque

---

Gemfile
Gemfile.lock
app/models/concerns/hyrax/collection_nesting.rb
spec/models/concerns/hyrax/collection_nesting_spec.rb

* When we save/update a collection, all its nested objects get reindexed. This slows down the process of saving a work. We update the save,update,delete callbacks to make sure we are using the limited reindexing strategy provided by Samvera:: NestingIndexer class instead of full. Refer: https://samvera.github.io/nested-indexing.html#nested-indexing-details

Changes reindex-extent to limited for collection nesting callbacks

---

app/views/manifest/manifest.json.jbuilder
spec/fixtures/sample-ocr.xml
spec/views/manifest/manifest.json.jbuilder_spec.rb

* We have PDF, OCR, and METS files for books which we don't need to display in UV or create images for them in the manifest. We are now only generating image sequences for file_sets that are not of type
pdf or xml.

Edits manifest jbuilder to ignore PDF and OCR files

---

solr/conf/schema.xml
solr/conf/solrconfig.xml
solr/config/schema.xml
solr/config/solrconfig.xml

* SolrSuggest may be responsible for slowdown in ingest pace. Disabling SolrSuggest might help to decrease time taken to create and add a work to a collection. Refer:
https://docs.google.com/presentation/d/1Jj0aC8LhfbcWxe0g8bBhTj1wxKMbkU6v11iJRBKNV3E/edit?copiedFromTrash#slide=id.g44d37b2273_2_0
and
https://docs.google.com/presentation/d/1Jj0aC8LhfbcWxe0g8bBhTj1wxKMbkU6v11iJRBKNV3E/edit?copiedFromTrash#slide=id.g44d37b2273_2_7
and
https://github.com/samvera/active_fedora/pull/1311/files

Disable SolrSuggest

---

app/presenters/hyrax/curate_generic_work_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/controllers/iiif_controller_spec.rb
spec/presenters/hyrax/curate_generic_work_presenter_spec.rb

* We are removing http from persistent URLs since this will be included in the env variable.

Removes http from purl

---

app/views/hyrax/collections/_show_descriptions.html.erb
spec/system/show_collection_spec.rb

* We are removing http from persistent URLs since this will be included in the env variable.
Connected to: #1144

Removes http from purl on collection show page

---

.gitignore
spec/jobs/check_binaries_job_spec.rb
spec/jobs/file_set_clean_up_job_spec.rb
spec/models/collection_spec.rb

When a test creates an artifact, it should clean up after itself and remove any files that got created during the test run. Otherwise, this could lead to unexpected side effects, and it's easy for these artifacts to accidentally get added to version control.

Remove test-created artifacts

---

app/indexers/year_parser.rb
spec/indexers/year_parser_spec.rb

Previously, dates recorded as "192X/193X" were parsed as "192" for Lux, leading to the date slider showing the wrong dates for these types of items
Before:
After:

Turn two uncertain decades into range of dates for Lux

---

app/models/solr_document.rb
app/presenters/hyrax/curate_generic_work_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/system/viewing_a_work_spec.rb

* We are displaying the correct visibility label for a work as a metadata field on the work view page.
Example:

Adds work visibility to work view page

---

config/sidekiq.yml

Some of our jobs are retrying multiple times very quickly, and we are
not changing code so quickly that we would expect the outcome to change.
Therefore, these retries are effectively spamming Honeybadger, making it
harder to sort through information to debug the underliying problem.
By changing to one retry by default, we should cut down on that spam,
and still get an opportunity for flaky errors to pass.

Limits job retries to one by default

---

Gemfile
Gemfile.lock
app/jobs/transfer_works_job.rb
lib/tasks/work_transfer.rake
spec/jobs/transfer_works_job_spec.rb

* We are also adding a call-stack profiler called stackprof to be able to study our internal classes and methods that are taking long durations to execute.
Once the job finishes running, it will create a stackprof dump file which can be viewed/examined using following two methods:
**1) Using a web ui** (This is the quickest way to view results locally): https://github.com/alisnic/stackprof-webnav
TLDR;
**install gem locally** 
```
$ gem install stackprof-webnav
```
**run the web ui server**
```
$ stackprof-webnav -f path/to/stackprof.dump
```
**go to web port**
```
localhost:9292
```
Result:
**2) Using console:** 
After running `bundle install` on your local machine, run the background job and follow steps to view stackprof dump file in the console and flamegraph in a viewer:
``` …
```

Adds a job to transfer works from one col to another

---

app/views/hyrax/base/_show_actions.html.erb
app/views/hyrax/dashboard/collections/_show_actions.html.erb
app/views/hyrax/my/_collection_action_menu.html.erb
app/views/hyrax/my/_work_action_menu.html.erb
spec/system/viewing_a_collection_spec.rb
spec/system/viewing_a_work_spec.rb

- Only allow admin users to see delete buttons and actions on work show page, my works dashboard page, all works dashboard page, my collections dashboard page, all collections dashboard page, and individual collection dashboard page

Restrict visibility of delete buttons

---

app/jobs/transfer_works_job.rb

* A large number of samples get generated when running our codeinside the profiler block. By passing the ignore_gc param we are hoping to ignore gc frames when generating a profile which might help to bring the number of frames down.

Ignore gc during code profile generation

---

app/views/hyrax/base/_preservation_status.html.erb
app/views/hyrax/base/show.html.erb
config/locales/hyrax.en.yml
spec/system/viewing_a_work_spec.rb

* Also, adds preliminary details like date uploaded, modified, depositor info to the new preservation status block.
Connected to: #1024 #1025 
Output:

Adds preservation status block to work view page

---

app/controllers/hyrax/curate_generic_works_controller.rb
app/controllers/hyrax/dashboard/collections_controller_override.rb
spec/controllers/hyrax/curate_generic_works_controller_spec.rb
spec/controllers/hyrax/dashboard/collections_controller_override_spec.rb

- Only admins can delete works and collections. When a non-admin user tries to submit an HTTP request for deletion, they get an unsuccessful response and are redirected to the Edit page.

Restrict delete methods to admins

---

app/presenters/hyrax/curate_generic_work_presenter.rb
app/views/hyrax/base/_preservation_status.html.erb
spec/presenters/hyrax/curate_generic_work_presenter_spec.rb
spec/system/viewing_a_work_spec.rb

* We are adding preservation workflow information for a work to the status block. The information is populated if it is supplied.
Output examples:

Adds preservation workflow info to status block

---

config/locales/hyrax.en.yml
spec/system/show_file_spec.rb

* This commit changes the download link text on fileset page from `download image` to `Download Preservation Master File`.
Connected to: #1033 
Before:
After:

Changes file download link text

---

app/controllers/hyrax/file_sets_controller.rb
app/views/hyrax/file_sets/show.html.erb
spec/system/show_file_spec.rb

- If a preservation master file for a fileset exists, display it in the files table on the fileset show page
- Move the files table to the desired place on the fileset show page

Display preservation master file in files table

---

app/assets/stylesheets/curate.scss
app/views/hyrax/file_sets/_show_details.html.erb
app/views/hyrax/file_sets/show.html.erb
config/locales/hyrax.en.yml
spec/system/show_file_spec.rb

- app/assets/stylesheets/curate.scss: styles the section for spacing and alignment.
- _show_details.html.erb: overrides the title call in localization.
- show.html.erb: moves the render call to the bottom.
- config/locales/hyrax.en.yml: adds new title to override old one.
- spec/*: injects tests that capture the title and field keys.

Moves File Details location and changes title #1034.

---

app/views/hyrax/file_sets/_show_actions.html.erb
app/views/hyrax/file_sets/show.html.erb
spec/system/show_file_spec.rb

* This commit removes social media sharing links from file_set show page as per requirements.
Before:
After:

Removes social media links

---

app/indexers/curate/file_set_indexer.rb
app/indexers/curate_generic_work_indexer.rb
app/models/preservation_event.rb
app/presenters/curate/file_set_presenter.rb
app/views/hyrax/file_sets/_preservation_events.html.erb
app/views/hyrax/file_sets/show.html.erb
config/locales/hyrax.en.yml
spec/indexers/curate_generic_work_spec.rb
spec/models/preservation_event_spec.rb
spec/system/show_file_spec.rb

Also refactors preservation events work on Generic Works Page.
- file_set_indexer.rb: adds preservation_event into solr_doc.
- curate_generic_work_indexer.rb: refactors method that provides the failed events json.
- preservation_event.rb: creates two new json mapping methods.
- file_set_presenter.rb: delegates :preservation_event to the solr_document.
- _preservation_events.html.erb: generates partial for the preservation events table.
- show.html.erb: calls the new partial from the show page.
- config/locales/hyrax.en.yml: institutes multiple headers for use in the new partial.
- spec/*: creates and refactors tests for the new partial.

Creates new Preservation Events table in FileSet view #1037.

---

app/assets/stylesheets/curate.scss
app/views/hyrax/file_sets/_preservation_events.html.erb

- app/assets/stylesheets/curate.scss: Makes the no events statement red.
- _preservation_events.html.erb: adds minimal styling and a wrapping <tr> around the table item blocks.

Wraps the table blocks in a table row (#1037) [Deploy 5/8/2020 or after].

---

app/models/concerns/hyrax/collection_behavior.rb
config/initializers/file_actor.rb

* Adds wings requirement to file_actor. Also corrects solr field name in collection behavior. We should now be able to run all rails commands and sidekiq.
Note: There is still an error running rubocop.
`Error: unrecognized cop Rails`

Adds wings requirement

---

app/jobs/characterize_job.rb
app/models/concerns/hyrax/file_set/characterization.rb
app/presenters/hyrax/characterization_behavior.rb
spec/factories/collections.rb
spec/jobs/characterize_job_spec.rb

* We are upgrading all previous overwritten files in `app/jobs` to hyrax3 beta3 with the new hyrax overwrite tag on top of files.
* Also, updating collections factory since it was copied from the previous hyrax version.
Adapting Brad's PR writing style:
`app/jobs/characterize_job.rb`: We are calling `alpha_channels` on the file and assigning it the file format. This is an addition in beta3.
`app/models/concerns/hyrax/file_set/characterization.rb`: defining new `alpha_channels` property.
`app/presenters/hyrax/characterization_behavior.rb`: Adding `alpha_channels` to characterization terms.
`spec/factories/collections.rb`: Updating collections factory to match beta3 collections factory.
`spec/jobs/characterize_job_spec.rb`: updating overwrite version tag and tests to match beta3 …

Upgrades overwritten jobs to beta3

---

app/models/concerns/hyrax/collection_behavior.rb
app/models/concerns/hyrax/collection_nesting.rb
app/models/concerns/hyrax/file_set/characterization.rb
app/models/file_set.rb
app/models/hyrax/uploaded_file.rb
app/models/solr_document.rb
config/initializers/file_actor.rb
spec/models/file_set_spec.rb

- curate.scss and _preservation_events.html.erb: incorporates commit left out of this branch that fixes lack of table row. 
- collection_behavior.rb: shifts away from Solrizer and ActiveFedora.base methods and institutes explicit field keys and new Hyrax.query_service calls.
- collection_nesting.rb: swaps out to newly defined Hyrax::SolrService method.
- characterization.rb: introduces alpha channel capability into manifests.
- app/models/file_set.rb: corrects the VirusChecker method call to the new module location.
- uploaded_file.rb: cleans up unnecessary callback.
- solr_document.rb: removes the Solrizer call in favor of explicitly naming field name.

Updates all model overrides and gem method calls to newer versions (#1239).

---

config/initializers/job_io_wrapper.rb
spec/models/job_io_wrapper_spec.rb

* When the size method in job_io_wrapper is called from active_fedora, we need it to return an integer instead of a string (it returns a string in Hyrax3-beta3 right now). We suspect that this works fine in beta3 since size method is called on an instance of Hyrax::UploadedFile class, and we are calling size method on a raw file. Therefore, we need to make sure its always an integer to successfully ingest files using AF.

Adds size class to job_io_wrapper

---

spec/lib/iiif_url_builder_service_spec.rb

- spec/lib/iiif_url_builder_service_spec.rb: found that the alternate id fileset was not being saved, so the pulling of the fileset object in dlp-curate/app/lib/iiif_url_builder_service.rb was returning an error. This saves the fileset and passes all errors.

Corrects fact that fileset with alternative is is never saved.

---

app/indexers/curate_generic_work_indexer.rb
app/models/solr_document.rb

- app/models/solr_document.rb and app/models/solr_document.rb: swaps field ending with _sim instead of _tesim.

Corrects errors caused by preservation workflow field. 

---

app/forms/hyrax/forms/collection_form.rb
app/models/concerns/hyrax/collection_behavior.rb
spec/factories/collections.rb
spec/system/iiif_access_controls_spec.rb

* app/forms/hyrax/forms/collection_form.rb: Removes `multiple` method which was previously causing error when loading collection form.
* app/models/concerns/hyrax/collection_behavior.rb: Updates hyrax version.
* spec/factories/collections.rb: updates collection title
* spec/system/iiif_access_controls_spec.rb: Updates `User-Agent`

Updates collection spec

---

app/services/date_service.rb
spec/services/date_service_spec.rb

- Provide human-readable dates for Lux in three additional scenarios:
- Known month with unknown year (e.g., "XXXX-10" -> "October (year unknown)")
- Known century with unknown decade (e.g., "20XX" -> "2000s")
- Uncertain year with unknown day and month (e.g., "1976~" -> "1976 approx.")

Cover additional human-readable dates

---

config/deploy.rb

In our `Gemfile`, Capistrano is allowed to update relatively liberally, but in the `config/deploy.rb`, it is more strictly locked. This change allows a more recent version.

Updates Capistrano

---

app/assets/stylesheets/curate.scss

* Bottom padding style has been set to 300px in hyrax, however, that causes a big height gap between the user activity table and preservation events table on the fileset page. We are setting that to 0px and overriding hyrax's style for the activity-display class.
Connected to: #1307

Edits activity-display class styling

---

app/forms/hyrax/curate_generic_work_form.rb
spec/system/create_curate_generic_work_spec.rb

* Giving users the ability to add a deduplication_key for a work through the form, this key can then be used to update data through various rake tasks/processes/imports.
Connected to: #1221

Adds deduplication_key to work form

---

app/views/hyrax/my/_search_form.html.erb
spec/factories/curate_generic_works.rb
spec/system/search_for_work_spec.rb

- The metadata fields included in the dashboard search bar are now brought in line with the fields searched in the main search bar. The following desired fields are explicitly tested:
- `deduplication_key`
- `other_identifiers`
- `id`
- `system_of_record_ID`
- `emory_ark`
- The values for three metadata fields in the `work_with_full_metadata` factory are made longer and unique so that their search functionality can be tested more accurately.

Include additional fields in dashboard search

---

config/initializers/rdf_uri_to_json.rb

* When calling `as_json` or `to_json` on an object, sometimes `RDF::JSON` already exists, which leads to name resolution failure. To stop this from happening, we are patching `JSON::LD` module with `::` in the beginning to ensure functions are performed at top level without `RDF` module.
Refer: https://github.com/samvera/valkyrie/pull/810

Fixes RDF::JSON::LD issue

---

app/controllers/catalog_controller.rb
spec/system/search_results_page_spec.rb

- app/controllers/catalog_controller.rb: moves away from using `solr`izing names and into explicitly calling fields.
- spec/*: creates tests for changes.

Makes missing facets display (#1190).

---

app/views/manifest/manifest.json.jbuilder
spec/controllers/iiif_controller_spec.rb
spec/services/manifest_builder_service_spec.rb
spec/views/manifest/manifest.json.jbuilder_spec.rb

* Sometimes we might need to hide file_sets from UV and not add them to manifests. We are adding a condition to check if the visibility for a file_set is restricted, if it is, do not add to manifest nor display in UV.
Connected to: #1044

Restricts addition of private fs in manifests

---

config/sidekiq.yml

Previously, jobs were only allowed to retry once before being pronounced dead. Now, they can retry three times. Each retry allows more time between the job failing and its next retry. Now, a job will spend 152 seconds total waiting between retries- up from just 30 before.

Adds more retries for background jobs before failing the job

---

config/authorities/rights_statements.yml

- "Copyright Varies by Work" is now available as a rights status for parent works whose child works do not have the same rights status.
- Instead of a URL, the value for this field is "Not Applicable." Lux will check for the presence of this value and conditionally render the rights status as a link based on whether it is a URL or not.

Add rights status for parent works

---

app/services/date_service.rb
spec/models/curate_generic_work_spec.rb
spec/services/date_service_spec.rb

- Corrects the human-readable format of date ranges with the type "193X/194X" from "within the 1930s or 1940s" to "1930s to 1940s"

Revise human readable date ranges

---

app/assets/javascripts/uv_width.js
app/assets/stylesheets/curate.scss
app/controllers/application_controller.rb
app/helpers/hyrax/iiif_helper.rb
app/values/uv_configuration.rb
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
config/routes.rb
config/uv/uv-config.json
config/uv/uv.html
config/uv/uv_config_liberal.json
package.json
spec/requests/uv_config_spec.rb
spec/routing/uv_config_routes_spec.rb
spec/support/visibility_curate_generic_works.rb
spec/values/uv_configuration_spec.rb

- app/assets/javascripts/uv_width.js: resizes the viewer to the container width.
- app/assets/stylesheets/curate.scss: styling that enforces the viewer to exist in desktop mode.
- app/controllers/application_controller.rb: pastes and slightly alters the actions from Lux' setup.
- app/helpers/hyrax/iiif_helper.rb: points the configuration to the uv route.
- app/values/uv_configuration.rb: imports model from Lux for configuration generation. 
- app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb: changes size and helper call.
- config/routes.rb: adds new route for json action.
- config/uv/uv-config.json and config/uv/uv_config_liberal.json: brings over the same code from Lux, even though this seems to only be there for redundancy.
- config/uv/uv.html: mirrors the Lux file.
- …

Matches the configuration of Curate UV to Lux (#1290).

---

app/views/hyrax/base/_form.html.erb
app/views/hyrax/my/works/index.html.erb
spec/system/create_curate_generic_work_spec.rb
spec/system/viewing_a_work_spec.rb

- Only admin users should see a batch upload link on the works dashboard. No users should see a batch upload link in the new work form.

Remove batch upload button

---

app/presenters/hyrax/curate_generic_work_presenter.rb
spec/controllers/iiif_controller_spec.rb
spec/presenters/hyrax/curate_generic_work_presenter_spec.rb
spec/services/manifest_builder_service_spec.rb

- app/presenters/hyrax/curate_generic_work_presenter.rb: swaps out just displaying value with formatting a link similar to "Persistent URL".
- spec/*: changes expectations for the link processing.

Changes Rights Status to a link with QA terms as text (#1191).

---

app/controllers/derivatives_controller.rb
app/jobs/file_set_clean_up_job.rb
app/views/hyrax/file_sets/show.html.erb
config/routes.rb
spec/controllers/derivates_controller_spec.rb

* We are adding a regen derivative button to fileset show page for on demand running of fileset cleanup on that particular fs.
* **app/controllers/derivatives_controller.rb**: Adds controller and its action for the on demand call to regen derivatives
* **app/jobs/file_set_clean_up_job.rb**: Modifies job to accept a single file_set_id argument instead of running on all file_sets, while keeping the option to run on all file_sets via rake task.
* **app/views/hyrax/file_sets/show.html.erb**: Adds button
* **config/routes.rb**: Adds route
* **spec/controllers/derivates_controller_spec.rb**: Controller spec
Connected to: #1284

Adds regen derivative button to fileset page

---

app/controllers/derivatives_controller.rb

Adds flash notice to derivative regen process so that users know to wait before retrying

---

app/models/curate_generic_work.rb
app/views/hyrax/base/_form.html.erb
app/views/hyrax/curate_generic_works/_form_url_validation_error.html.erb
spec/system/create_curate_generic_work_spec.rb

* We are adding more specific errors messages to the red error banner provided by simpleform when url validation failures occur.
OUTPUT:

Adds errors message to banner on url validation failure

---

app/controllers/hyrax/fixity_checks_controller.rb
app/jobs/fixity_check_job.rb
app/services/hyrax/file_set_fixity_check_service.rb
lib/tasks/fixity_check.rake
spec/jobs/fixity_check_job_spec.rb
spec/services/hyrax/file_set_fixity_check_service_spec.rb

- app/controllers/hyrax/fixity_checks_controller.rb: includes the current user's `uid` as `initiating_user` argument.
- app/jobs/fixity_check_job.rb: brings in the new `initiating_user` argument and uses it instead of `fixity_file_set.depositor`.
- app/services/hyrax/file_set_fixity_check_service.rb: overrides the hyrax service to accept the new argument.
- lib/tasks/fixity_check.rake: hardcodes the preferred user value into the rake call associated.
- spec/*: inserts the expectation for the `initiating_user` argument.

Replaces the depositor of the file with the current_user uid (#1264).

---

app/views/hyrax/my/collections/_batch_actions.html.erb
app/views/hyrax/my/works/_bactch_actions.html.erb
spec/system/viewing_a_collection_spec.rb
spec/system/viewing_a_work_spec.rb

* We are removing delete, edit, and add to collections buttons for non-admin users. We are also removing delete collections button for the same.

Remove delete buttons for non-admin users

---

app/jobs/collection_files_ingested_job.rb
lib/tasks/collection_files_ingested.rake

- app/jobs/collection_files_ingested_job.rb: protects against `sha1_tesim` being nil.
- lib/tasks/collection_files_ingested.rake: points the user to the right folder.

Fix files ingested collection job 1252

---

app/jobs/create_derivatives_job.rb
spec/jobs/create_derivatives_job_spec.rb

* Sometimes when create derivatives for a fileset, there might be a mini magick error which leads to failure of the job. Currently, we are not logging any file details when this failure happens. This
commit helps mitigate that problem.
* **app/jobs/create_derivatives_job.rb**: Adds more logging options for info and failure
* **spec/jobs/create_derivatives_job_spec.rb**: Adds spec to confirm warnings are logged when minimagick errors occur.

Adds logging for imagemagick errors when creating thumbs

---

app/indexers/curate_collection_indexer.rb
spec/indexers/collection_indexer_spec.rb

- app/indexers/curate_collection_indexer.rb: formats path without caring what comes before `/branding`.
- spec/indexers/collection_indexer_spec.rb: checks that formatting is working using a path we have in `test` envirnoment.

Formats the banner path agnostically (#672).

---

app/views/hyrax/dashboard/collections/_show_actions.html.erb
app/views/hyrax/dashboard/collections/_show_subcollection_actions.html.erb
spec/system/viewing_a_collection_spec.rb

- app/views/hyrax/dashboard/collections/_show_actions.html.erb: adds admin requirement to button code.
- app/views/hyrax/dashboard/collections/_show_subcollection_actions.html.erb: brings in hyrax file to add admin restraint. 
- spec/system/viewing_a_collection_spec.rb: expands testing to check for these elements' ids.

Suppresses the SubCollection related buttons/links for non-admins (#1336).

---

app/assets/stylesheets/curate.scss
app/presenters/hyrax/collection_presenter.rb
app/views/hyrax/collections/_show_descriptions.html.erb
app/views/hyrax/collections/show.html.erb
app/views/hyrax/dashboard/collections/_show_descriptions.html.erb

- app/assets/stylesheets/curate.scss: adjusts the styling of the elements addressed in the ticket.
- app/presenters/hyrax/collection_presenter.rb: removes the display value of size, per request by @eporter23 made on 7/31/20 via DM on slack.
- app/views/hyrax/collections/_show_descriptions.html.erb: strips `dl` structure in favor of a straight bootstrap column approach.
- app/views/hyrax/collections/show.html.erb: brings in the page as override to excise exact column sizing.
- app/views/hyrax/dashboard/collections/_show_descriptions.html.erb: once again removes dl structure fo that label-top/value-bottom is maintained.

Styles the collection view pages and removes size from listed metadata (#1267).

---

app/services/hyrax/sensitive_material_service.rb
spec/system/create_curate_generic_work_spec.rb

- app/services/hyrax/sensitive_material_service.rb: overrides the QA method so that it delivers Yes and No.
- spec/system/create_curate_generic_work_spec.rb: tests that the labels are correct.

Changes sensitive material labels to Yes and No (#1347).

---

README.md

The old option of Coveralls seems to have had a hard transition from the `master` branch to `main`.

Changes test coverage badge to CodeClimate

---

app/views/hyrax/base/_form_visibility_component.html.erb
spec/system/create_curate_generic_work_spec.rb

- When a user selects the public visibility option in the new work form, they are no longer presented with a warning

Remove inapplicable warning for public works

---

app/controllers/catalog_controller.rb
spec/system/search_results_page_spec.rb

- app/controllers/catalog_controller.rb: removes unwanted fields, adds requested ones, and tailors all of their labels.
- spec/system/search_results_page_spec.rb: tests all fields that are populating.

Changes the fields show on the search result list (#1346).

---

app/lib/preservation_events.rb
spec/system/create_curate_generic_work_spec.rb

* When creating a work, object gets a save call for preservation_events which kicks off url validations. At this point we save the object only if there aren't any errors, else take them back to the create page.

Adds guard clause to check if object has any errors before saving

---

app/importers/yellowback_preprocessor.rb
spec/fixtures/csv_import/yellowbacks/yellowbacks_marc.xml
spec/importers/books_preprocessor_metadata_spec.rb
spec/importers/curate_mapper_spec.rb
spec/models/curate_generic_work_spec.rb

- app/importers/yellowback_preprocessor.rb: adds manipulation logic to import dates correctly.
- spec/fixtures/csv_import/yellowbacks/yellowbacks_marc.xml: alters date so that new preprocessor method can produce an example.
- spec/importers/books_preprocessor_metadata_spec.rb: inserts context concerning how date should be converted to 4-digit year.
- spec/models/curate_generic_work_spec.rb and spec/importers/curate_mapper_spec.rb: makes these tests reflect the expected standard date for `date_digitized` from here on out.

Updates yellowback preprocessor with `date_digitized` adjustment (#915).

---

spec/system/create_curate_generic_work_spec.rb

The LoC authorities in QA appear to not return the proper json at the moment, so we'll skip this test until we can get that fixed.

Skips failing QA test

---

app/indexers/curate_generic_work_indexer.rb
app/models/curate_generic_work.rb
spec/indexers/curate_generic_work_spec.rb
spec/lib/curate_generic_work_attributes_spec.rb
spec/models/curate_generic_work_spec.rb
spec/system/create_curate_generic_work_spec.rb

* We are adding a new metadata field that will store the source_collection_id on the work.

Adds initial work for collection overload strategy

---

app/models/user.rb
app/views/hyrax/my/works/index.html.erb
spec/models/user_spec.rb
spec/system/viewing_a_work_spec.rb

- app/models/user.rb: creates method that tests whether user has `viewer` role.
- app/views/hyrax/my/works/index.html.erb: makes "Add new work" button useable to only non-"viewer" roles.
- spec/*: tests functionality of user method and its integration.

Hides Add new work button when user role contains viewer (#1309).

---

.rubocop.yml
app/controllers/background_jobs_controller.rb
app/jobs/preservation_workflow_importer_job.rb
app/views/background_jobs/new.html.erb
app/views/hyrax/dashboard/sidebar/_tasks.html.erb
config/routes.rb
spec/controllers/background_jobs_controller_spec.rb
spec/fixtures/reindex_files.csv
spec/jobs/preservation_workflow_importer_job_spec.rb
spec/system/admin_dashboard_spec.rb

- Curate administrators can load preservation workflow metadata by submitting a CSV in the UI
- The work should happen in a background job
Resolves #1319

creates ui and functionality for background jobs in admin dashboard

---

app/importers/curate_mapper.rb
spec/importers/curate_mapper_spec.rb

The test for missing curate property is failing because @devanshu-m has been working on the related ticket adding property to fedora and solr.

adds additional field to the mapper

---

.rubocop.yml
app/presenters/hyrax/collection_presenter.rb
config/locales/en.yml
spec/presenters/collection_presenter_spec.rb
spec/system/show_collection_spec.rb
spec/system/viewing_a_collection_spec.rb

- app/presenters/hyrax/collection_presenter.rb: removes visibility constriction.
- config/locales/en.yml: changes header text.
- spec/presenters/collection_presenter_spec.rb: pulls in the spec from the Hyrax gem and focuses purely on changed method.
- spec/system/viewing_a_collection_spec.rb: adds expectations for the altered header.

Changes label and count focus for Items on Collection index (#1405).

---

app/models/solr_document.rb
app/presenters/hyrax/curate_generic_work_presenter.rb
app/views/hyrax/base/_relationships_parent_rows.html.erb
spec/system/viewing_a_work_spec.rb

**app/models/solr_document.rb**: Adds raw solr field to `source_collection_title` method
**app/presenters/hyrax/curate_generic_work_presenter.rb**: adds delegation for `source_collection_title`
**app/views/hyrax/base/_relationships_parent_rows.html.erb**: Show source collection if it exists and if it is different from deposit collection
**spec/system/viewing_a_work_spec.rb**: spec to test display when source collection is present and absent
Output:

Adds source collection details to work show page

---

app/indexers/curate_collection_indexer.rb
app/models/collection.rb
config/solr_wrapper_test.yml
spec/indexers/collection_indexer_spec.rb
spec/models/collection_spec.rb

In order to relate a source collection to its deposit collections (see wireframe showing a Source Collection showing a link to its Deposit Collection) we anticipate needing one or two metadata fields at the Collection level:
These would follow the same pattern as established for work-level equivalents for SOLR and Fedora.
source_collection_id
http://metadata.emory.edu/vocab/cor-terms#sourceCollectionID
deposit_collection_id
http://metadata.emory.edu/vocab/cor-terms#depositCollectionID

Adds relationship metadata fields to Collection model

---

app/views/hyrax/file_sets/show.html.erb
spec/system/show_file_spec.rb

- app/views/hyrax/file_sets/show.html.erb: deletes `single_use_links` render call.
- spec/system/show_file_spec.rb: tests that Single-Use HTML doesn't appear.

Removes the Single-Use Links section from FileSet show page (#1414).

---

app/views/hyrax/base/show.html.erb
spec/system/viewing_a_work_spec.rb

- app/views/hyrax/base/show.html.erb: omits the Social Media and Citation buttons.
- app/views/hyrax/base/show.html.erb: adds tests making sure they're gone.

Removes Citation and Social Media buttons from Works view page (#1415).

---

app/presenters/hyrax/admin_set_presenter.rb
app/presenters/hyrax/collection_presenter.rb
spec/factories/admin_sets.rb
spec/presenters/hyrax/admin_set_presenter_spec.rb

app/presenters/hyrax/admin_set_presenter.rb: brings in Hyrax code for override. Changes the `total_viewable_items` scope to `total_items`. Would have imported the `spec` file as well, but the file didn't test this method.

Changes total_viewable_items to not care about viewability (#1405).

---

config/initializers/works_controller.rb
spec/system/viewing_a_work_spec.rb

Connected to: #1406 
* We are adding a new dropdown facet to the works dashboard index page. This dropdown will be used to search by source collections.
* **config/initializers/works_controller.rb**: Opens up `works_controller` and appends to the `configure_facets` method.
* **spec**: Tests to make sure dropdown is present and absent in different scenarios.
Output:

Adds source collection dropdown facet

---

app/indexers/curate_generic_work_indexer.rb
spec/indexers/curate_generic_work_indexer_spec.rb

A new manifest cache key needs to generated if a work's visibility is changed. This will in turn trigger manifest regen when the work show page is visited.

Adds work's visibility when calculating manifest cache hash key

---

app/helpers/collection_show_helper.rb
app/presenters/hyrax/collection_presenter.rb
app/views/hyrax/collections/_source_collection.html.erb
app/views/hyrax/collections/show.html.erb
app/views/hyrax/dashboard/collections/show.html.erb
spec/presenters/collection_presenter_spec.rb
spec/system/viewing_a_collection_spec.rb

- app/helpers/collection_show_helper.rb: reverts to a helper to create the link since additional logic to form appropriate destination was needed.
- app/presenters/hyrax/collection_presenter.rb: alters method so that it delivers a value hash, not a link.
- app/views/hyrax/collections/_source_collection.html.erb: instigates partial since this will show on two separate pages.
- app/views/hyrax/collections/show.html.erb: renders partial instead of html code.
- app/views/hyrax/dashboard/collections/show.html.erb: overrides the Hyrax show page so that source collection link can be included.
- spec/*: switches out expectations to accommodate more views and different method.

Partializes the Source Collection links in Collection show pages (#1390).

---

app/indexers/curate_collection_indexer.rb
spec/indexers/collection_indexer_spec.rb

- app/indexers/curate_collection_indexer.rb: corrects the pulling of the title array by choosing the first title.
- spec/indexers/collection_indexer_spec.rb: provides multiple ids so that we can test the processing titles.

Ensures that multiple deposit collection titles are indexed properly (#1456).

---

app/helpers/collection_show_helper.rb
app/indexers/curate_collection_indexer.rb
app/presenters/hyrax/collection_presenter.rb
app/search_builders/hyrax/collection_member_search_builder.rb
app/views/hyrax/collections/_deposit_collections.html.erb
app/views/hyrax/collections/_source_collection.html.erb
app/views/hyrax/collections/show.html.erb
app/views/hyrax/dashboard/collections/show.html.erb
config/locales/en.yml
spec/indexers/collection_indexer_spec.rb
spec/presenters/collection_presenter_spec.rb
spec/system/viewing_a_collection_spec.rb

- Display links to all of a source collection's deposit collections on the source collection show page (both dashboard and public versions)
- On the source collection show page, display all the source collection's works as well as its deposit collection's works
- Search against works in the source collection and its deposit collections on the source collection show page
- Generalize `#source_collection_link` to be simply `#collection_link` to accommodate deposit collection links
- Rename `#deposit_collection_object` to `#source_collection_object` to better reflect its purpose and to avoid confusion with new method `#deposit_collections`
**Source collection show page (dashboard):**
**Source collection show page (public):**

Show deposit collections on source collection page

---

.rubocop.yml
app/controllers/characterization_controller.rb
app/jobs/characterize_job.rb
app/jobs/re_characterize_job.rb
app/services/re_characterization_service.rb
app/views/hyrax/file_sets/show.html.erb
config/locales/hyrax.en.yml
config/routes.rb
spec/controllers/characterization_controller_spec.rb
spec/jobs/re_characterize_job_spec.rb
spec/presenters/hyrax/admin_set_presenter_spec.rb
spec/services/re_characterization_service_spec.rb
spec/system/show_file_spec.rb

- .rubocop.yml: skips `characterize_job` file for rubocop failure when adding new argument.
- app/controllers/characterization_controller.rb: creates new action that starts a re-characterization by pressing a button on the file_set show page. Please note, I understand the preference that the action be associated with the closest relative controller, but attempting to do so produced errors that I couldn't find a quick fix for, so I left this action separate.
- app/jobs/characterize_job.rb: adds `user` argument in case of the Characterization taking place from a controller action.
- app/jobs/re_characterize_job.rb: institutes an individual job for the re-characterization of the preservation_master_file.
- app/services/re_characterization_service.rb: brought processing over to a service …

Adds button to re-characterize file set (#1283).

---

app/jobs/collection_files_ingested_job.rb
spec/jobs/collection_files_ingested_job_spec.rb

- app/jobs/collection_files_ingested_job.rb: restricts the collections to Source Collections and the works to those having matching `source_collection_id`s. 
- spec/jobs/collection_files_ingested_job_spec.rb: assigns a `source_collection_id` to collection.

Updates Collection File Rake Task to focus on source_collection_id (#1436).

---

app/forms/hyrax/curate_generic_work_form.rb
spec/forms/hyrax/curate_generic_work_form_spec.rb
spec/system/create_curate_generic_work_spec.rb

- Admin users can now specficy a work's source collection on the new/edit work form
- `spec/system/create_curate_generic_work_spec.rb` is updated to make the default user an admin in order for the source collection dropdown to show up

Add source_collection_id to work form

---

app/controllers/manifest_regeneration_controller.rb
app/views/hyrax/base/_show_actions.html.erb
config/locales/hyrax.en.yml
config/routes.rb
spec/controllers/manifest_regeneration_controller_spec.rb

* We are adding a manifest regen button for admins to manually regen manifests
on demand.
* **app/controllers/manifest_regeneration_controller.rb**: Adds logic to delete existing manifest for a work if it exists and then call the manifest builder service to create a new manifest.
* **app/views/hyrax/base/_show_actions.html.erb**: Adds button
* **config/routes.rb**: Adds route
* **spec/controllers/manifest_regeneration_controller_spec.rb**: Adds tests
Output:

Adds manifest regen button

---

app/views/records/edit_fields/_source_collection_id.html.erb
spec/system/create_curate_generic_work_spec.rb

- The partial for `source_collection_id` on the new/edit form now checks for whether the form is for a work or a collection. That way, works can require `source_collection_id` without also making it required for collections.

Require source_collection_id on works

---

app/indexers/curate_generic_work_indexer.rb
spec/indexers/curate_generic_work_indexer_spec.rb

* There are instances when the order of the rendering_ids in its array gets messed up and we end up with different hash keys whenever a work is reindexed. To be able to have consistency, we are making sure we first sort the array and then pass it for hash generation. We are also checking to make sure holding repo is always single valued (in case the solr field value is used which is an array).

Improving manifest key generation in work indexer

---

lib/tasks/README.md

`lib/tasks/README.md`:
- L# 25-30: all of the arguments are required.
- L# 41, 44: need to denote Source Collection.
- L# 45: warns user that ids need to come from Source Collections.
- L# 64: since determination of if a file has been modified has changed, have removed the line that refers to the old process.

Updates the Rake task README with corrected verbiage (#1435).

---

app/jobs/characterize_job.rb
app/jobs/re_characterize_job.rb
spec/jobs/characterize_job_spec.rb
spec/jobs/re_characterize_job_spec.rb

- app/jobs/characterize_job.rb: makes the user variable a positional argument.
- app/jobs/re_characterize_job.rb: lines up the argument values in the CharacterizeJob call.
- spec/*: tests the expected outcome for the user assignment.

Fixes the passing of username into Characterize Job (#1283).

---

app/views/catalog/_index_list_default.html.erb
spec/system/search_results_page_spec.rb

Connected to: #1490 
* We are adding logic to display the source col for a work on the search results page if source collection is present. If source and deposit cols are same, do nothing.

Adds logic to display source col on search results page

---

app/controllers/catalog_controller.rb
app/indexers/curate_generic_work_indexer.rb
spec/system/search_results_page_spec.rb

- The collections facet now uses `source_collection_title_for_works_ssim` instead of `member_of_collections_ssim`
- `source_collection_title_for_works_ssim` is created in order for the collections facet to show only works (`source_collection_title_ssim` is also indexed for collections)
- `search_results_spec.rb` is revised to account for the fact that no source collections exist at that point in the system test, reducing the number of applicable facets to 12

Use source collection for faceting

---

app/jobs/characterize_job.rb
config/initializers/characterization_service.rb
spec/jobs/characterize_job_spec.rb
spec/jobs/re_characterize_job_spec.rb
spec/services/characterization_service_spec.rb

- app/jobs/characterize_job.rb: passes the user to the the service if present.
- config/initializers/characterization_service.rb: overrides the `run` and `initialization` methods so they accept a user argument. Also establishes a `@user` instance variable that can be used in the event creation.
- spec/jobs/characterize_job_spec.rb and spec/jobs/re_characterize_job_spec.rb: changes `rspec` expectation for new argument.
- spec/services/characterization_service_spec.rb: checks that initiating user's `uid` is assigned correctly.

Points the Message Digest Calculation event point to initiating user when processing Recharacterization (#1283).

---

app/controllers/catalog_controller.rb
app/indexers/curate_collection_indexer.rb
app/indexers/curate_generic_work_indexer.rb
app/presenters/hyrax/collection_presenter.rb
spec/indexers/collection_indexer_spec.rb
spec/system/search_results_page_spec.rb

- This PR accomplishes the same behavior as #1497, but instead of indexing a new field on works, we are indexing a new field on collections. This way, only collections will have to be re-indexed in order for faceting by source collection to function properly.
- See #1497 for the specs. Every change from that PR is reversed in this one except for the specs.

Facet works by source collection

---

app/views/hyrax/base/_show_actions.html.erb
spec/system/viewing_a_work_spec.rb

- app/views/hyrax/base/_show_actions.html.erb: adds admin requirement for Add to collection button.
- spec/system/viewing_a_work_spec.rb: tests for existence of button when user admin/non.

Suppresses Add to collection button on Works page when user non-admin (#1504).

---

app/helpers/hyrax/collections_override_helper.rb
spec/helpers/hyrax/collections_override_helper_spec.rb

`app/helpers/hyrax/collections_override_helper.rb`:
> This overrides only one helper method in `Hyrax::CollectionsHelper`, namely `render_collection_links(solr_doc)`. Lines 10 and 11 are the only changes where we are pulling source collections attached to the work, and integrating them into the `collections_list` array that the "Is Part Of:" is fed from.
Note: I couldn't get rspec to load the "Dashboard > All Works" page after associating the work with the deposit collection (e.g. `work.member_of_collections << deposit_collection`). Because of this, I have left with out of the system rspec tests.

Displays Source alongside Deposit Collection in Is Part Of on Dashboard Works (#1479).

---

app/presenters/hyrax/admin_set_presenter.rb
app/presenters/hyrax/collection_presenter.rb

Error link: https://app.honeybadger.io/projects/66999/faults/68124506
Summary: Since it makes little sense to define a method in a child Presenter and also call it in the parent Presenter, I have moved the definition to the parent and completely deleted it from the child. Since `Hyrax::AdminSetPresenter` already inherits from `CollectionPresenter`, it will automatically be available in both after the changes.
Changes:
- app/presenters/hyrax/admin_set_presenter.rb: excises the `managed_access` method definition.
- app/presenters/hyrax/collection_presenter.rb: replaces the call to it's child Presenter method with the actual definition.

Possible fix to the error referenced in Honeybadger for Managed Collections view (#1516).

---

.rubocop.yml
app/actors/hyrax/actors/create_with_files_actor.rb
app/jobs/attach_files_to_work_job.rb
spec/actors/hyrax/actors/create_with_files_actor_spec.rb
spec/jobs/attach_files_to_work_job_spec.rb

- .rubocop.yml: allows Hyrax-imported spec to pass rubocop linting.
- app/actors/hyrax/actors/create_with_files_actor.rb: passes initiating user to the AttachFilesToWorkJob.
- app/jobs/attach_files_to_work_job.rb: takes in and makes the initiating user the priority for the user associated for the File Attached change event.
- spec/*: changes expectations for arguments passed through as well as makes sure that the `FileSetAttachedEventJob` gets the right user.

Changes FileSet Attachment Event to reflect initiating user (#1249).

---

app/actors/hyrax/actors/create_with_files_actor.rb

app/actors/hyrax/actors/create_with_files_actor.rb: adjusts the order of the arguments since a hash argument should be last.

Moves the attributes hash to the end of the argument chain in attach_files (#1249).

---

app/views/hyrax/base/_show_actions.html.erb
spec/system/viewing_a_work_spec.rb

Because the feature button breaks other functionality, we are removing it from work show pages for all users.
**Before:**
**After:**

Remove feature button from work show page

---

app/services/hyrax/file_set_fixity_check_service.rb
config/initializers/hyrax.rb
lib/tasks/fixity_check.rake

* We are seeing a large number of fixity check errors which may be caused because of an overwhelming number of file requests sent to s3. We are adding a sleep statement for 1 second in an attempt to let the file be retrieved and processed successfully.
* We are also adding an argument to limit the number of filesets we run fixity check on. This is only for testing purposes.
* Also changing the max days between fixity check via ui to 1. Again, this is only for testing purposes.

Attempts to fix fixity check issues caused on the server

---

app/views/zizia/csv_imports/_collection_selection.html.erb

app/views/zizia/csv_imports/_collection_selection.html.erb: utilizes already created helper to ensure that all Collections show in select options.

Diverts collections options to already created custom helper (#1522).

---

config/sidekiq.yml

* Putting queues in order of their weightage and adding additional limit configuration in an attempt to make fixity_check_job to use the fixity_check_job queue.

Adds additional limit param to fixity check job queue

---

config/schedule.rb
lib/tasks/fixity_check.rake

* We need to check for presence of limit arg when running fixity check rake task, else it assigns zero if it doesn't see a value. So making a change to first check for presence, if not presence go with fileset total count.
* Also changing when cron runs rake task to wednesday on curate-test for testing purposes.

Improves limiting fixity check for filesets

---

app/indexers/curate_collection_indexer.rb
app/jobs/collection_files_ingested_job.rb
app/models/collection.rb
spec/models/collection_spec.rb

- app/indexers/curate_collection_indexer.rb: swaps out the `member_works_count_isi` value to the number of works with matching `source_collection_id`.
- app/jobs/collection_files_ingested_job.rb: removes the variables for the service and builders, since they are now not repeated. Also points the pulling of works to a newly created class method.
- app/models/collection.rb: creates a new class method that returns an array of Solr objects that are related to a source collection.
- spec/models/collection_spec.rb: changes expectations for the 'member_works_count_isi' count to reflect the matching of `source_collection_id`.

Corrects member_works_count_isi scope to Works with matching source_collection_id (#693).

---

app/controllers/catalog_controller.rb
spec/system/search_results_page_spec.rb

- app/controllers/catalog_controller.rb: inserts two new fields to display in search result snippet.
- spec/system/search_results_page_spec.rb: tests for existence of label.

Adds deduplication_key and id to the search results snippet (#1444).

---

app/views/hyrax/homepage/index.html.erb
spec/system/viewing_homepage_spec.rb

- app/views/hyrax/homepage/index.html.erb: removes logic that delivers both links.
- spec/system/viewing_homepage_spec.rb: adds test to check for removal of links.

Removes two unnecessary links from the homepage (#1511).

---

config/locales/hyrax.en.yml
spec/system/create_curate_generic_work_spec.rb

- config/locales/hyrax.en.yml: changes verbiage.
- spec/system/create_curate_generic_work_spec.rb: tests the existence of the correct verbiage.

Expands Admin abbreviation in labels for clarity (#1478).

---

app/views/hyrax/base/_attribute_rows.html.erb
spec/system/viewing_a_work_spec.rb

- app/views/hyrax/base/_attribute_rows.html.erb: renders nothing when confronting `preservation_event`, `preservation_workflow`, and `preservation_workflow_terms`.
- spec/system/viewing_a_work_spec.rb: makes sure the unwanted terms/values are not present.

Removes the Preservation Event and Workflow listings on Work show page (#1501).

---

app/helpers/hyrax/ability_override_helper.rb
spec/system/filtering_on_dashboard_works_spec.rb

- app/helpers/hyrax/ability_override_helper.rb: overrides Hyrax helper to instead read the `visibility_ssi` field.
- spec/system/filtering_on_dashboard_works_spec.rb: tests expectations.

Corrects the visibility badges for works on Dashboard (#1545).

---

app/indexers/curate_generic_work_indexer.rb
spec/indexers/curate_generic_work_indexer_spec.rb

- app/indexers/curate_generic_work_indexer.rb: adds the file sets' visibility to the hex.
- spec/indexers/curate_generic_work_indexer_spec.rb: tests for the string to be present.

Ties changes to File Set visibility to Manifest Regeneration (#1591).

---

config/schedule.rb

* We are commenting out whenever cron job schedule so as to not have fixity run as scheduled.
Refer: #1633

Suspend fixity checking until further notice

---

app/controllers/background_jobs_controller.rb
app/views/background_jobs/new.html.erb
spec/controllers/background_jobs_controller_spec.rb

- app/controllers/background_jobs_controller.rb: adds the preprocessor options to the create action.
- app/views/background_jobs/new.html.erb: inserts the three different preprocessors into the form used for background jobs.
- spec/controllers/background_jobs_controller_spec.rb: tests for new processes and refactors other tests to alleviate deprecation warnings.

Automates preprocessors in UI (#1567).

---

app/assets/javascripts/application.js
app/assets/javascripts/curate_hyrax.js
app/assets/stylesheets/curate_hyrax.scss
app/assets/stylesheets/hyrax.scss

- app/assets/javascripts/application.js: points to our customized Javascript instead of the Gem file.
- app/assets/javascripts/curate_hyrax.js: brings in the hyrax.js file from Hyrax 3.1.0, minus the browse_everything code.
- app/assets/stylesheets/curate_hyrax.scss: creates an alternate version of Hyrax v3.1.0 hyrax.scss that removes browse_everything code.
- app/assets/stylesheets/hyrax.scss: inserts a requirement to our code in the exact place the last call was made.

Bug fix: jquery.treetable error.

---

config/initializers/file_actor.rb
config/initializers/job_io_wrapper.rb
config/initializers/works_controller.rb

- config/initializers/file_actor.rb: uses new method created for v3.1.0.
- config/initializers/job_io_wrapper.rb: bumps the version number.
- config/initializers/works_controller.rb: makes the search_builder_class a part of the config, per v3.1.0.

Brad's Initializers work.

---

app/models/curate/collection_type.rb
spec/controllers/characterization_controller_spec.rb
spec/controllers/derivates_controller_spec.rb
spec/controllers/hyrax/downloads_controller_spec.rb
spec/controllers/hyrax/file_sets_controller_spec.rb
spec/controllers/hyrax/fixity_checks_controller_spec.rb
spec/controllers/hyrax/uploads_controller_spec.rb
spec/controllers/manifest_regeneration_controller_spec.rb

- app/models/curate/collection_type.rb: changes the super plus method to an `after_initialize` callback.
- spec/*: replaces `success?` with `successful?` to eliminate deprecation warnings.

Fixes errors for CollectionType model and success? deprecation (#1680).

---

spec/requests/iiif_requests_spec.rb

**spec/requests/iiif_requests_spec.rb**: Mocking using `with` is giving errors, and not using it passes all tests. This maybe a webmock update.

Updates specs to make requests test suite green

---

spec/models/collection_spec.rb
spec/models/concerns/hyrax/collection_behavior_spec.rb

Update to collection_spec here is concerning because `item` arg for initialization of the MultipleMembershipChecker class expects a CurateGenericWork which we are providing but is being passed an a Hyrax::Work (valkyrie). I am not sure why this is happening.

Updates model specs

---

app/controllers/hyrax/curate_generic_works_controller.rb
app/models/concerns/hyrax/file_metadata.rb
app/models/concerns/hyrax/file_set/characterization.rb
spec/actors/hyrax/actors/curate_generic_work_actor_spec.rb

- app/controllers/hyrax/curate_generic_works_controller.rb: makes clear that `ManifestBuilderService` is our own service and not the Hyrax class.
- app/models/concerns/hyrax/file_metadata.rb: addresses our PCDM use cases in the new code.
- app/models/concerns/hyrax/file_set/characterization.rb: updates version number.
- spec/actors/hyrax/actors/curate_generic_work_actor_spec.rb: makes tests aware of new argument.

Fixes errors.

---

app/controllers/hyrax/file_sets_controller.rb
app/helpers/hyrax/file_set_helper.rb
spec/services/characterization_service_spec.rb

spec/services/characterization_service_spec.rb: I confirmed that the reason this now returns an empty array instead of a hash is because the `reload` method calls a function pulled from ActiveModel's Dirty module, which has changed with an update. The last line of that method (`clear_attribute_changes`) in version 5.1.7 operates on a hash of values and returns an empty hash, fulfilling it's purpose. In version 5.2.6, however, that last line is followed by an each statement that further operates on each attribute, therefore returning an empty array. Since the line of this test is checking to make sure the file reloads as expected and we are not using the return value of reload in our application, changing the expectations here is harmless. Proof: …

Updates Characterization Service's spec to expect array (#1680).

---

app/controllers/manifest_regeneration_controller.rb
spec/controllers/manifest_regeneration_controller_spec.rb

- app/controllers/manifest_regeneration_controller.rb: removes the regeneration method since it's called automatically when the controller redirects to the show page.
- spec/controllers/manifest_regeneration_controller_spec.rb: adjusts expectations to reflect the omission of the Regen method call.

Bug: eliminates duplicate Manifest Regeneration jobs (#1637).

---

app/helpers/hyrax/ability_override_helper.rb
app/views/hyrax/dashboard/collections/_show_actions.html.erb
app/views/hyrax/my/_collection_action_menu.html.erb

All: adds `data:  { turbolinks: false }` to the links, disabling the use of cache to load the edit destination pages.

Turns off Turbolinks cache call on edit page links (#1780).

---

app/controllers/background_jobs_controller.rb
app/jobs/process_aws_fixity_preservation_events_job.rb
app/lib/preservation_events.rb
app/models/aws_fixity_event.rb
app/views/background_jobs/new.html.erb
lib/tasks/aws_fixity_check.rake
spec/controllers/background_jobs_controller_spec.rb
spec/fixtures/csv_import/aws_fixity_test.csv
spec/jobs/process_aws_fixity_preservation_events_job_spec.rb
spec/models/aws_fixity_event_spec.rb

- app/controllers/background_jobs_controller.rb: adds new CSV batch processing to the Background Jobs controller, as well as refactors the similar csv actions to a generic action call.
- app/jobs/process_aws_fixity_preservation_events_job.rb: creates a background job for batch AWS Fixity event processing.
- app/lib/preservation_events.rb: allows PreservationEvents to receive a variable for event start.
- app/models/aws_fixity_event.rb: initiates a class to properly process and test event hash structure.
- app/views/background_jobs/new.html.erb: adds the new background option to the view.
- lib/tasks/aws_fixity_check.rake: provides an option to process CSVs through a rake task.
- spec/*: tests all aspects of the new tool.

Loads AWS Fixity Events from CSV (#1658).

---

app/models/aws_fixity_event.rb
spec/jobs/process_aws_fixity_preservation_events_job_spec.rb
spec/models/aws_fixity_event_spec.rb

All: removes space from in-between sha1 label and value, per request.

Refines the AWS details text (#1658).

---

config/sidekiq.yml

Needed to lower the failure rate of Bulkrax imports.

Reduces the import job max to 10.

---

app/presenters/hyrax/collection_presenter.rb

Updates the methods that perfectly match the original version's functions. 
Note: Collection Branding is updated here and may be worthwhile revisiting this file if we encounter problems displaying the collections' banners.

Updates the affected methods of Hyrax::CollectionPresenter (#1868).

---

app/jobs/fixity_check_job.rb
config/initializers/hyrax.rb

- app/jobs/fixity_check_job.rb: swaps out to the new procedure while integrating our preservation logging work.
- config/initializers/hyrax.rb: moves to defining the fixity service in the config initializer so that others can be easily swapped to.

Updates the affected methods of FixityCheckJob (#1863).

---

app/models/curate/collection_type.rb
spec/models/curate/curate_collection_type_spec.rb
spec/models/hyrax/collection_type_spec.rb

- app/models/curate/collection_type.rb: With the bump up of Ruby, calling super initialize causes an error here. Instead, I have passed the `configure` method to a `after_initialize` callback. I have also found that the changes made to `.any_nestable?` in Hyrax v3.4.1 don't operate as intended, so I have brought that method into our override.
- spec/models/curate/curate_collection_type_spec.rb: Here, I have placed the tests found in `spec/models/hyrax/collection_type_spec.rb` for `.any_nestable?` and adapted them to work inside this test file.
- spec/models/hyrax/collection_type_spec.rb: Updated to closely match the Hyrax v3.4.1 version of this file.

Fixes the spec revolving around CollectionType (#1921).

---

spec/models/curate_generic_work_spec.rb

Nothing about our code or Hyrax' has changed about the way this value is processed (see below).
```
def iso8601_date(value)
if value.is_a?(Date) || value.is_a?(Time)
DateTime.parse(value.to_s).to_time.utc.strftime('%Y-%m-%dT%H:%M:%SZ')
elsif !value.empty?
DateTime.parse(value).to_time.utc.strftime('%Y-%m-%dT%H:%M:%SZ')
end
rescue ArgumentError
raise ArgumentError, "Unable to parse `#{value}' as a date-time object"
end
```
My suspicion is that the return value of `DateTime.parse` has changed with the Ruby version change we're instituting. Hopefully, this doesn't break anything in the system, especially in facets, but the good thing there is that this value is treated as only a reference for `human_readable_data_collection_dates`, which does it's own further parsing.

Fixes the spec revolving around CurateGenericWork (#1921).

---

spec/actors/hyrax/actors/curate_generic_work_actor_spec.rb

Ticket #1921
Resolves spec failures of file `dlp-curate/spec/actors/hyrax/actors/curate_generic_work_actor_spec.rb`
In Hyrax `v3.4.1`, method `run_callbacks(hook, env)` defined in `app/actors/hyrax/actors/base_actor.rb` is defined as:
```ruby
def run_callbacks(hook, env)
Hyrax.config.callback.run(hook, env.curation_concern, env.user, warn: false)
true
end
```
Our specs were missing the `warn: false` in the parameters expected to be passed to `Hyrax.config.callback.run`.

Resolve curate generic work actor spec failures

---

.rubocop.yml
app/models/hyrax/uploaded_file.rb
spec/controllers/hyrax/file_sets_controller_spec.rb

Summary: This is a case where, technically, this should have failed before now, but gracefully passed. The failing test ` Hyrax::FileSetsController when signed in #update when updating the attached file direct upload spawns a ContentNewVersionEventJob` was expecting an `uploader` attribute from `UploadedFile` that was an alias of the one type of `UploadedFileUploader` that Hyrax supports out of the box. We have overridden that class to allow multiple types of file to be saved to the object. Because we don't need `uploader`(we assign the path argument further down the chain), we simply commented it out and the tests were happy. 
Now, this test (`spec/controllers/hyrax/file_sets_controller_spec.rb` L# 113) is checking for the presence of any method named `uploader`, so I've created one that …

Fixes the spec revolving around Hyrax::FileSetsController (#1921).

---

app/jobs/fixity_check_job.rb

Summary: Reworks the override so that we can do our `Preservation Event`ing solely within the perform method, which also fixes our error.

Fixes the spec revolving around FixityCheckJob (#1921).

---

spec/presenters/hyrax/admin_set_presenter_spec.rb

Summary: I found that Samvera had experienced the same errors, and they fixed them by persisting the offending objects rather than purely initializing them.

Corrects the flakiness of the Hyrax::AdminSetPresenter spec by creating FactoryBot objects (#1912).

---

app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
spec/system/admin_dashboard_spec.rb
spec/system/bulkrax_csv_import_spec.rb

- app/views/hyrax/dashboard/sidebar/_repository_content.html.erb: overrides Bulkrax' customized partial to add in admin protections.
- spec/*: tests that the above changes work.

Show Bulkrax sidebar links only to admins (#1939).

---

.rubocop.yml
config/initializers/bulkrax.rb
lib/importing_modules/file_set_methods.rb

- config/initializers/bulkrax.rb: pulls the uploaded files first, and then processes the preferred file outside of the iterations.
- lib/importing_modules/file_set_methods.rb
- removes the preferred value being pulled from the creation process
- updates the preferred file method to look at all uploaded files at once.

Sets the preferred file for derivatives before iterating over files (#1944).

---

app/actors/hyrax/actors/file_set_actor.rb
app/jobs/associate_filesets_with_work_job.rb
app/jobs/attach_files_to_work_job.rb
config/initializers/bulkrax.rb
lib/importing_modules/file_set_methods.rb
spec/actors/hyrax/actors/curate_generic_work_actor_spec.rb

- app/actors/hyrax/actors/file_set_actor.rb: moves this callback to just after the FileSet/Work association point.
- app/jobs/associate_filesets_with_work_job.rb: creates a separate job that associates all of the FileSets going into a work at once.
- app/jobs/attach_files_to_work_job.rb: since we're processing the FileSet/Work association here instead of inside `file_set_actor`, this moves the callback to right after that association.
- config/initializers/bulkrax.rb: 
- removes the index/number of files details as arguments since we're now doing the FileSet/Work association that needed that information to its own Job.
- overrides the Bulkrax::ScheduleRelationshipsJob so that we can insert a call to the new AssociateFilesetsWithWorkJob at the end of the ingest process.
- …

Moves FileSet association to Work to the end of the ingest process (Bulkrax only).

---

spec/system/viewing_a_user_spec.rb

Resolve test failures in `spec/system/viewing_a_user_spec.rb`
Previously, search result titles were displayed within `h4` tags. In Hyrax `3.4.2`, they now are displayed within `h3` tags.

Resolve viewing user specs

---

spec/system/viewing_a_work_spec.rb

Resolve test failures in `spec/system/viewing_a_work_spec.rb`. To view the batch upload link, the `Flipflop` feature `batch_upload?` has to be enabled, which is not explicitly set in the test. The changes in this PR explicitly set that feature to `true` in the failing test.

Resolve test failures in `spec/system/viewing_a_work_spec.rb`

---

app/jobs/associate_filesets_with_work_job.rb
config/emory/index_file_set_results.csv

This eliminates the need to not have `-cor` in a dedupe key.

Refines the finding of the parent work (#1955).

---

app/matchers/bulkrax/csv_matcher.rb

Summary: brings back code that was originally removed from https://github.com/emory-libraries/dlp-curate/pull/1851, but adds a missing field and better aligns the needed FileSet fields to parse.

Reimplements parser fields switch with missing field.

---

app/views/hyrax/dashboard/collections/_form.html.erb

Originally, this value in Hyrax v3.0.0.pre.rc1 was tied to `f.object.thumbnail_title`, but at sometime in the past, we preferred the FS id to display instead. The rspec test was checking for that customization, which was removed in favor of Hyrax v3.4.2's new helper method. I'm reversing that choice.

Reverting the thumbnail dropdown option to our original override.

---

.rubocop.yml
app/controllers/background_jobs_controller.rb
app/importers/dams_preprocessor.rb
spec/importers/dams_preprocessor_bulkrax_spec.rb

Requirements to meet: 
- The deduplication_key column should only be populated for works, not FileSets.
- The model column is the same as Zizia’s type column, but should be formatted as:
- CurateGenericWork for work rows
- FileSet for fileset rows 
- The parent column should contain:
- For works, the source_collection_id or the Curate ID for the deposit collection if one exists. 
- For filesets, the deduplication_key for the work the fileset is attached to.
- The title field should include the value currently stored in fileset_label for FileSet entries. Currently the preprocessor repeats the work title.
- The file column contains a list of all the filenames to attach to each fileset, separated by a semicolon. They should formatted such as the following:
- 0001.tif;0001.txt
- If we are …

Creates Bulkrax-specific option for the DAMS Preprocessor (#1984).

---

app/controllers/background_jobs_controller.rb
app/importers/yellowback_preprocessor.rb
spec/fixtures/csv_import/yellowbacks/yellowbacks_marc.xml
spec/importers/books_preprocessor_metadata_spec.rb
spec/importers/kirtas_preprocessor_file_bulkrax_spec.rb
spec/importers/limb_preprocessor_file_spec.rb

- app/controllers/background_jobs_controller.rb: updates the argument list since the Replacement argument is no longer used.
- app/importers/yellowback_preprocessor.rb: 
- removes the unwanted replacement path option.
- adds importer argument to enable feature switching.
- unfreezes the header_fields so that they can be interpolated into.
- refactors and alters logic to accommodate for bulkrax.
- removes the errant | (pipes) from populating in contributors.
- excises .pos (extracted) from delivering for kirtas imports.
- fixes copyright_date
- spec/fixtures/csv_import/yellowbacks/yellowbacks_marc.xml: ensures there's at least one copyright value in the merged CSV.
- spec/importers/kirtas_preprocessor_file_bulkrax_spec.rb: updates the expectations of the spec file below.
- …

Updates the kirtas side of Yellowbacks for Bulkrax (#1984).

---

.rubocop.yml
app/importers/yellowback_preprocessor.rb
spec/importers/limb_preprocessor_file_bulkrax_spec.rb
spec/models/job_io_wrapper_spec.rb

- .rubocop.yml: refactors the rubocop yaml for ease of reading and adds to it.
- app/importers/yellowback_preprocessor.rb:
- removes the repetitive rubocop dis/enabling to clean up the file.
- adds the ability to add COR and Transcript lines (if not already present) when checked in the UI.
- DRYs up blocks that either need or don't need own methods.
- spec/importers/limb_preprocessor_file_bulkrax_spec.rb: largely copies and adds onto the `spec/importers/limb_preprocessor_file_spec.rb` file.
- spec/models/job_io_wrapper_spec.rb removes rubocop disablement because I included it into the yaml instead.

Updates the limb side of Yellowbacks for Bulkrax (#1984).

---

app/jobs/manifest_persistence_job.rb
app/services/manifest_builder_service.rb
spec/services/manifest_builder_service_spec.rb

Fixes #2002
Based on feedback from @eporter23 and @rotated8, I implemented the following in this PR:
- When no manifest exists for a Work, in addition to queueing a Sidekiq job to regenerate the manifest, we now also save a placeholder manifest file. This ensures each subsequent request to view the Work does not queue an additional duplicate manifest regeneration job. While the manifest regeneration job is processed, each request for the manifest of a Work will still receive a response with the placeholder manifest, which is generated using the file `app/views/manifest/placeholder.json.jbuilder`
- Before saving the newly generated manifest, we now delete all outdated manifest files, to ensure we only keep one accurate manifest per work, and avoid keeping outdated files.

Fix manifest regeneration duplicate jobs

---

app/models/ability.rb
spec/models/ability_spec.rb

- Add `ability_spec.rb` with tests for the custom permissions we have for admins
- Remove unnecessary admin check for Zizia related abilities in `ability.rb`

Add ability_spec

---

app/controllers/csv_import_details_controller.rb
config/routes.rb
spec/controllers/csv_import_details_controller_spec.rb
spec/system/sidekiq_dashboard_spec.rb

- Add `csv_import_details_controller_spec.rb` to ensure only admin users can access `csv_import_details` related pages
- Edit `routes.rb` to remove the `csv_import_details` routes from authenticated routes. Upon further testing, I figured that the admin status verification was not properly done, so non-admin users could load `csv_import_details` if we did not enforce the `CanCanCan` rules at the controller level. Therefore, I added the `CanCanCan` rules to the `csv_import_details_controller.rb` and removed those routes from the authenticated routes.
- Add a test for non-authenticated users to `spec/system/sidekiq_dashboard_spec.rb` to ensure they are redirected to the sign in page and cannot access the Sidekiq dashboard.

Add Sidekiq and csv import details tests

---

app/jobs/associate_filesets_with_work_job.rb

The locking of the work has been backfiring on importation. Instead of ensuring that the work is free and clear to be persisted upon (which really shouldn't be an issue because this is the last Job to perform during the import), the built-in timeout of the locking is lapsing because each 
```
work.save
work.update_index
```
take about five minutes or longer to complete. I believe the lock is set to 4 minutes, which probably leads to the two recent issues in the production environment (the reindexing after saving not happening and the recent work not having the FileSets associated.)

Removes the redlock and extra update_index from the FS association job.

---

app/assets/javascripts/application.js
app/assets/javascripts/newspaper_works/ocr_search.js.erb
app/assets/stylesheets/_search_results.scss
app/assets/stylesheets/curate.scss
app/controllers/catalog_controller.rb
app/helpers/hyrax_helper.rb
app/helpers/newspaper_works/newspaper_works_helper_behavior.rb
app/lib/newspaper_works/highlight_search_params.rb
app/models/curate_generic_work.rb
app/models/search_builder.rb
app/views/catalog/_snippets_more.html.erb
config/locales/blacklight.en.yml

Implements #2063
In this PR, I used the OCR search implementation from the Samvera [newspaper_works](https://github.com/samvera-labs/newspaper_works) to implement keyword matches highlighting for search results. See example below:
The reason I use some files from the `newspaper_works` gem directly instead of installing an entire version using bundler is the current dependence of the gem on Hyrax v2, and the unavailability of any official release that supports Hyrax v3. In this PR, I only use files from v1.0.2 of the gem to server our specific use case, which is displaying keyword matches under search results, for any results that actually have full text data that matches the keywords searched.

Add keyword matches to search results

---

app/assets/javascripts/application.js
app/javascript/packs/application.js
app/views/bulkrax/importers/index.html.erb
package.json
spec/system/create_collection_spec.rb
spec/system/create_curate_generic_work_spec.rb
yarn.lock

- app/assets/javascripts/application.js: before this change, we were working with the combo of jQuery 1 and Bootstrap3 Datatables. Since we are using both jQuery3 and Bootstrap 4, this code makes clear what is required by the application.
- app/javascript/packs/application.js: removes the other reference to jQuery 1, bringing the application into v3.
- app/views/bulkrax/importers/index.html.erb: 
- changes the date/time format so that they are easily sortable.
- default sorts by `Last Run` column, so that it shows the latest import at the top of the list.
- corrects the columns that should be sortable.
- package.json and yarn.lock: brings in the new javascript requirements.

Corrects the problems blocking custom sorting options in Importer index.

---

app/actors/hyrax/actors/file_set_actor.rb
app/jobs/attach_files_to_work_job.rb

Please see comments around code for reference.

Moves a callback causing errors from FileSetActor to job that calls actor.

---

app/views/manifest/manifest.json.jbuilder
spec/fixtures/manifest_output.rb
spec/fixtures/sample-text.txt
spec/views/manifest/manifest.json.jbuilder_spec.rb

Fixes #2074 
Per Emily's request, we do not want the full text data file sets to show up in the IIIF viewer after they are generated. Emily requested to exclude .txt files from the viewer.

Disable display of .txt files in iiif viewer

---

.rubocop.yml
app/views/bulkrax/exporters/_form.html.erb
config/initializers/bulkrax.rb
lib/bulkrax/export_assistive_methods.rb
lib/bulkrax/ingest_assistive_methods.rb
lib/bulkrax/override_assistive_methods.rb
spec/system/bulkrax_csv_export_spec.rb

- .rubocop.yml: allows exceptions for new Bulkrax overrides.
- app/views/bulkrax/exporters/_form.html.erb: adds in `export_source_object_ids` as a new exporting type.
- config/initializers/bulkrax.rb:
- L#331 and L#442-476: hijacks these methods to allow new option to process.
-  deletions: removes assistive methods to their own Modules to reduce possible Code Climate issues.
- lib/*: refactors the containing modules so that the module names are more descriptive, they are grouped by how they assist, and that including one module still contains all methods.

Adds the Object IDs type to the exporter.

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css
app/views/bulkrax/importers/index.html.erb
package.json
yarn.lock

- app/assets/*: requires the libraries necessary to make this filtering possible.
- app/views/bulkrax/importers/index.html.erb: adjusts the script to initiate SearchPane Filtering.
- package.json and yarn.lock: installs the datatable libraries needed to make the filtering functional.

Makes Bulkrax' importer status filterable.

---

app/views/hyrax/dashboard/sidebar/_repository_content.html.erb

Since the Javascript code wasn't loading when returning to the Importer#index page after moving away from it (a common Turbolinks bug), I have turned off Turbolinks on both index pages so that current and future filtering can load without fail.

BUG FIX: Turns off Turbolinks from Dashboard's Importer and Exporter links.

---

app/models/ability.rb
config/initializers/bulkrax.rb
spec/system/admin_dashboard_spec.rb
spec/system/bulkrax_csv_export_spec.rb
spec/system/bulkrax_csv_import_spec.rb

- app/models/ability.rb: new permissions were undesired.
- config/initializers/bulkrax.rb: because the setter method and the "get" methods are different for this one file type, it is necessary to convert the filetype when exporting.
- spec/*: this is reverting the changes that were needed to test the new permissions.

Revisions to Bulkrax v5 behaviour.

---

.rubocop.yml
app/jobs/characterize_job.rb
spec/jobs/characterize_job_spec.rb

- .rubocop.yml: bumps up the Ruby version to our current.
- app/jobs/characterize_job.rb: 
- the FS shows as not yet characterized because the Solr index hasn't updated in-between the Characterization process. `update_index` added after the persistence runs. 
- moves the preservation event for Characterization creation to after the save and index updating of the FileSet.
- because we clear characterization metadata before characterizing, checking for presence of any of those values is proof of characterization and that can be used for the preservation events.
- spec/jobs/characterize_job_spec.rb: since we don't actually characterize a true file (connecting the tools in various test environments is problematic), we can only test for Characterization Failure here.

Update Solr index for FileSet after characterization.

---

app/controllers/aspace_controller.rb
app/services/aspace/formatting_service.rb
spec/services/aspace/formatting_service_spec.rb

- Per QA feedback, we need to map `holding_repository` for "Emory University Archives" to "Stuart A. Rose Manuscript, Archives, and Rare Book Library"
- Refactored `formatting_service.rb` and `aspace_controller.rb` to improve readability

Refactor formatting service

---

app/jobs/process_aws_fixity_preservation_events_job.rb
app/lib/preservation_events.rb
app/models/aws_fixity_event.rb
spec/jobs/process_aws_fixity_preservation_events_job_spec.rb
spec/lib/preservation_events_spec.rb

- app/jobs/process_aws_fixity_preservation_events_job.rb: stops processing the line if we already have a Fixity event that matches.
- app/lib/preservation_events.rb: first pulls the Fixity events that perfectly match the date provided from CSV, and then checks if the SHA1 in question has an event tied to it. The `select` calls are separated here because Fixity events are structured differently that others due to `event_details` values. Running `event_details.first.include?` on different types of Events throws errors.
- app/models/aws_fixity_event.rb: made `fixity_start` readable outside of the class so that we can call `check_for_preexisting_preservation_events` with the value.
- spec/*: tests expectations.

Avoids creating duplicates when processing AWS Fixity CSV.

---

app/views/hyrax/dashboard/collections/new.html.erb

- Expand "Additional Fields" whenever data is autopopulated. This ensures the user is aware of all data that was autopopulated and that is hidden under additional fields.
- Reset fields to one empty input when data is autopopulated and no values are available. This prevents a scenario where values from an older transaction are not removed properly on the UI.

Fix Aspace Autopopulate UI

---

app/controllers/background_jobs_controller.rb
app/jobs/replace_work_members_job.rb
app/jobs/work_members_clean_up_job.rb
app/views/background_jobs/new.html.erb
spec/controllers/background_jobs_controller_spec.rb
spec/jobs/replace_work_members_job_spec.rb
spec/jobs/work_members_clean_up_job_spec.rb

Fixes the effects of intermittent "shoveling" of duplicate or nil objects into Works' ordered members (FileSets). These tools relieves issues like this: https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/gh/emory-libraries/dlp-curate/2237

Adds WorkMembersCleanUpJob.

---

app/controllers/hyrax/dashboard/collections_controller_override.rb
app/views/hyrax/dashboard/collections/new.html.erb

This reverts commit c57dfd0460e9fe2b74c5079c2e9abf236e0066ea.

Revert "Moves the loading of Aspace repositories to the controller action (#2168). (#2230)"

---

app/indexers/curate/file_set_indexer.rb
app/models/file_set.rb
spec/fixtures/book_page/0003_alto.xml
spec/fixtures/book_page/0003_transcript.txt
spec/indexers/curate/file_set_indexer_spec.rb
spec/models/file_set_spec.rb

- app/indexers/curate/file_set_indexer.rb: adds new fields to indexer.
- app/models/file_set.rb: creates text pulling logic in FileSet model.
- spec/fixtures/book_page/0003_alto.xml: creates testing fixture for ALTO XML.
- spec/fixtures/book_page/0003_transcript.txt: replaces text file with corrupted contents. Needed to replace this because previous tests never worked with transcript file's contents before and doing so exposed that previous file didn't meet UTF-8 expectation.
- spec/*: adds testing of expected indexing and model behavior.

Adds full text fields to Fileset indexing.

---

app/assets/stylesheets/_work_show_page.scss
app/controllers/full_text_indexing_controller.rb
app/jobs/reindex_object_children_job.rb
app/views/hyrax/base/_show_actions.html.erb
config/routes.rb
spec/controllers/full_text_indexing_controller_spec.rb
spec/jobs/reindex_object_children_job_spec.rb
spec/routing/full_text_indexing_routing_spec.rb
spec/system/viewing_a_work_spec.rb

- app/assets/stylesheets/_work_show_page.scss: styles the new pulldown.
- app/controllers/full_text_indexing_controller.rb: adds new action and refactors the processing into private methods.
- app/jobs/reindex_object_children_job.rb: creates new Job class that reindexes a work's child members.
- app/views/hyrax/base/_show_actions.html.erb: changes the Full Text Indexing to a dropdown button.
- spec/*: updates the tests' expectations.

Adds option to reindex child pages to work show page.

---

app/views/manifest/manifest.json.jbuilder
spec/views/manifest/manifest.json.jbuilder_spec.rb

- app/views/manifest/manifest.json.jbuilder: checks for both the presence of `alto_xml_tesi` in the FileSets and `all_text_timv` in the Work before initiating the IIIF Search service in the manifest.
- spec/views/manifest/manifest.json.jbuilder_spec.rb: tests the expectations laid out above.

Allows IIIF Search only when Work has all_text field.
