.env.development, app/actors/hyrax/actors/curate_generic_work_actor.rb, app/controllers/hyrax/curate_generic_works_controller.rb, app/forms/hyrax/curate_generic_work_form.rb, app/indexers/curate_generic_work_indexer.rb, app/models/curate_generic_work.rb, app/presenters/hyrax/curate_generic_work_presenter.rb, app/views/hyrax/curate_generic_works/_curate_generic_work.html.erb, config/initializers/hyrax.rb, config/locales/curate_generic_work.de.yml, config/locales/curate_generic_work.en.yml, config/locales/curate_generic_work.es.yml, config/locales/curate_generic_work.fr.yml, config/locales/curate_generic_work.it.yml, config/locales/curate_generic_work.pt-BR.yml, config/locales/curate_generic_work.zh.yml, lib/admin_setup.rb, lib/tasks/ci.rake, spec/actors/hyrax/actors/curate_generic_work_actor_spec.rb, spec/controllers/hyrax/curate_generic_works_controller_spec.rb, spec/features/create_curate_generic_work_spec.rb, spec/forms/hyrax/curate_generic_work_form_spec.rb, spec/models/curate_generic_work_spec.rb, spec/presenters/hyrax/curate_generic_work_presenter_spec.rb
=> create curate generic work type

app/models/curate_generic_work.rb, spec/models/curate_generic_work_spec.rb
=> adding description metadata part 4

.rubocop.yml, app/models/curate_generic_work.rb, spec/models/curate_generic_work_spec.rb
=> add descriptive metadata part 5

app/models/curate_generic_work.rb, spec/models/curate_generic_work_spec.rb
=> Adds descriptive metadata part 3

app/models/curate_generic_work.rb, spec/models/curate_generic_work_spec.rb
=> implements rights metadata

.solr_wrapper, Gemfile, README.md
=> Ci documentation

app/models/curate_generic_work.rb, spec/models/curate_generic_work_spec.rb
This commit adds admin metadata to CurateGenericWork model
Closes #91
=> Adds admin metadata

app/models/curate_generic_work.rb, spec/models/curate_generic_work_spec.rb
This commit updates metadata properties as noted by Emily
Refer: https://docs.google.com/document/d/1YdpzK_22o3YPb1qF8axEmSRA17TWr1-hj7RaT6Q6cZQ/
Connected to #131
=> Updates metadata properties as required

app/models/curate_generic_work.rb, app/validators/type_validator.rb, spec/models/curate_generic_work_spec.rb, spec/validators/type_validator.rb
=> implements custom date validation

Gemfile, Gemfile.lock, app/forms/hyrax/curate_generic_work_form.rb, spec/features/create_curate_generic_work_spec.rb, spec/forms/hyrax/curate_generic_work_form_spec.rb, spec/rails_helper.rb
This commit adds our metadata properties to form. Also adds `webdrivers` gem (which includes `selenium-webdriver`)
Closes #134
=> Adds metadata properties to hyrax form

app/forms/hyrax/curate_generic_work_form.rb, spec/features/create_curate_generic_work_spec.rb, spec/rails_helper.rb
Adds required metadata properties to hyrax form. 
Also edits selenium `timeout` method to `read_timeout` because of deprecation warning.
Closes #136
=> Adds required fields for form

app/models/file_set.rb, spec/models/file_set_spec.rb
=> Ensures Hyrax supports multi-part objects

spec/features/create_curate_generic_work_spec.rb, spec/forms/hyrax/curate_generic_work_form_spec.rb
=> Ensures repeating entries repeat in the form

app/models/curate_generic_work.rb, app/validators/url_validator.rb, spec/features/create_curate_generic_work_spec.rb, spec/support/new_curate_generic_work_form.rb, spec/validators/url_validator_spec.rb
=> Adds URI validation

app/assets/javascripts/application.js, app/assets/javascripts/hyrax/autocomplete/default.es6, spec/features/create_curate_generic_work_spec.rb, spec/models/curate_generic_work_spec.rb
=> Adds ability to save custom terms for fields that use external vocabs

.circleci/config.yml
Reverts emory-libraries/dlp-curate#197
=> Revert "Changes Circle workflow name, and uses published Samvera Orb"

app/controllers/omniauth_callbacks_controller.rb, app/models/user.rb, config/routes.rb, spec/models/user_spec.rb
=> Prevents new users from getting an account

app/forms/hyrax/curate_generic_work_form.rb, app/models/curate_generic_work.rb, app/views/hyrax/base/_form_metadata.html.erb, app/views/records/edit_fields/_data_classification.html.erb, app/views/records/edit_fields/_institution.html.erb, app/views/records/edit_fields/_re_use_license.html.erb, spec/features/create_curate_generic_work_spec.rb, spec/models/curate_generic_work_spec.rb, spec/support/new_curate_generic_work_form.rb
Also updates required fields, tests, and edits license to re-use-license
Connected to #134 
Connected to #136 
Connected to #141
=> Updates form-fields groups

.circleci/config.yml
Uses an updated Samvera orb that provides a working bundle command, and adds a yarn cache.
=> Circle update

package.json, yarn.lock
Updates yarn packages to resolve a security vulnerability for fstreamer, and adds webpack to package.json, to silence the unmet peer dependency warnings.
=> Updates yarn packages

babel.config.js
This fixes a warning the test suite was emitting.
=> Adds corejs version for babeljs

app/actors/hyrax/actors/file_set_actor.rb, app/controllers/hyrax/uploads_controller.rb, app/jobs/attach_files_to_work_job.rb, app/views/hyrax/base/_form_files.html.erb, db/migrate/20190620155826_add_use_to_uploaded_files.rb, db/schema.rb, spec/features/create_curate_generic_work_spec.rb, spec/features/fileset_uploader_spec.rb, spec/jobs/attach_files_to_work_job_spec.rb, spec/support/new_curate_generic_work_form.rb, spec/support/wait_for_ajax.rb
* Adds a field for selecting if fileset is primary or supplementary
* Edits job to save the selection for fileset use as a metadata property
* Adds ability for cloning fileset inputs with unique element ids
=> Edits form to enable adding multiple filesets

app/forms/hyrax/forms/collection_form.rb, app/models/collection.rb, spec/features/create_collection_spec.rb, spec/forms/hyrax/forms/collection_form_spec.rb
=> Adds validations for collection metadata properties

app/assets/javascripts/hyrax/save_work/save_work_control.es6, app/javascript/validation/index.js
=> fixes string saving and minimum 4 number

app/assets/javascripts/hyrax/app.js.erb, app/assets/javascripts/hyrax/collections/editor.es6, app/views/collections/edit_fields/_administrative_unit.html.erb, app/views/collections/edit_fields/_holding_repository.html.erb, app/views/hyrax/dashboard/collections/_form.html.erb
=> Adds QA and autocomplete for collection metadata form

app/views/collections/edit_fields/_related_material.html.erb, app/views/records/edit_fields/_abstract.html.erb, app/views/records/edit_fields/_access_right.html.erb, app/views/records/edit_fields/_author_notes.html.erb, app/views/records/edit_fields/_contact_information.html.erb, app/views/records/edit_fields/_data_source_note.html.erb, app/views/records/edit_fields/_grant.html.erb, app/views/records/edit_fields/_internal_rights_note.html.erb, app/views/records/edit_fields/_legacy_rights.html.erb, app/views/records/edit_fields/_note.html.erb, app/views/records/edit_fields/_parent_title.html.erb, app/views/records/edit_fields/_related_material.html.erb, app/views/records/edit_fields/_scheduled_rights_review_note.html.erb, app/views/records/edit_fields/_sensitive_material_note.html.erb, app/views/records/edit_fields/_staff_note.html.erb, app/views/records/edit_fields/_table_of_contents.html.erb, app/views/records/edit_fields/_technical_note.html.erb, app/views/records/edit_fields/_title.html.erb, spec/features/create_collection_spec.rb, spec/features/create_curate_generic_work_spec.rb
=> Replaces single-line text inputs with multi-line text areas

.rubocop.yml, .rubocop_todo.yml, app/models/concerns/hyrax/file_set/characterization.rb, app/models/schemas/curate_file_schema.rb, config/initializers/add_metadata_scheme.rb, spec/jobs/characterize_job_spec.rb, spec/models/concerns/hyrax/file_set/characterization_spec.rb, spec/models/file_set_spec.rb
=> Changes characterization_proxy from original_file to PMF

config/routes.rb, spec/features/sidekiq_dashboard_spec.rb
Mount it at /sidekiq
Only someone who is logged in as an admin can reach it
Connected to https://github.com/curationexperts/dlp-curate/issues/6
=> Add sidekiq web UI

config/deploy.rb, config/deploy/cd.rb, config/deploy/dce_localhost.rb, config/deploy/qa.rb, lib/tasks/dce_accounts.rake
Also, add DCE continuous deployment server to deploy settings
Connected to https://github.com/curationexperts/dlp-curate/issues/28
=> Automate DCE account creation

config/locales/hyrax.en.yml, spec/features/create_curate_generic_work_spec.rb, spec/support/new_curate_generic_work_form.rb
=> removes help text from the work form and updates form labels

.rubocop.yml, lib/tasks/sample_data.rake
Connected to https://github.com/curationexperts/in-house/issues/184
Connected to https://github.com/curationexperts/in-house/issues/185
=> Metadata load

lib/tasks/sample_data.rake
* Ensure sample data has a depositor (otherwise file attachment won't work)
* Use URIs for a couple of required fields
=> Metadata fixes

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.css
This updates the version of Zizia to include
CSS and JS path changes and includes the Zizia
JS and CSS in the app.
=> Update version of Zizia

Gemfile, Gemfile.lock, spec/system/importer_guide_spec.rb
This updates the version of Zizia and adds
a spec that tests that the importer guide page is
rendering.
=> Update Zizia for guide changes

Gemfile, Gemfile.lock
This updates Zizia version to fix an issue where the CSV would be uploaded to 
a path that didn't exist.
=> Update Zizia for path fix

app/controllers/hyrax/file_sets_controller.rb, app/views/hyrax/file_sets/_file_details.html.erb, app/views/hyrax/file_sets/show.html.erb, spec/features/show_file_spec.rb
=> Edits fileset view page to add file details for additional files

.circleci/config.yml
The goal is test coverage is available on [Code Climate](https://codeclimate.com/github/emory-libraries/dlp-curate)
=> Adds CodeClimate to CircleCI setup.

app/models/curate/collection_type.rb, spec/models/curate/curate_collection_type_spec.rb
Connected to https://github.com/emory-libraries/dlp-curate/issues/394
=> Curate collection type participants

app/assets/javascripts/hyrax/save_work/save_work_control.es6, app/javascript/validation/index.js, app/views/layouts/application.html.erb
=> fixes JS date validation

app/models/collection.rb, app/models/curate_generic_work.rb, app/models/file_set.rb, config/initializers/hyrax.rb, config/initializers/noid_rails.rb, spec/models/curate_generic_work_spec.rb, spec/rails_helper.rb
=> fixes noid minting

app/services/parent_query_service.rb, app/views/hyrax/base/_parent_relationship_table.html.erb, app/views/hyrax/base/_relationships_parent_rows.html.erb, config/locales/hyrax.en.yml, spec/services/parent_query_service_spec.rb
=> adds parent child relationship in show page

lib/tasks/dce_accounts.rake
Connected to https://github.com/emory-libraries/dlp-curate/issues/444
=> Don't assign admin role if it is already assigned

.rubocop.yml, config/collection_metadata/yearbooks_collection.csv, config/collection_metadata/yellowbacks_collection.csv, config/deploy.rb, lib/tasks/curate_collections.rake
Connected to https://github.com/emory-libraries/dlp-curate/issues/403
=> Auto-create yellowbacks and yearbooks collections

.rubocop.yml, app/controllers/hyrax/dashboard/collections_controller_override.rb, app/importers/curate_collection_importer.rb, app/lib/solr_document_accessors.rb, app/models/collection.rb, app/models/curate/collection_type.rb, app/presenters/hyrax/curate_collection_presenter.rb, app/views/hyrax/dashboard/collections/new.html.erb, config/application.rb, spec/fixtures/csv_import/collections/langmuir_collection.csv, spec/importers/curate_collection_importer_spec.rb, spec/system/create_collection_spec.rb, spec/system/show_collection_spec.rb
Connected to https://github.com/emory-libraries/dlp-curate/issues/387
=> Display collection metadata

lib/tasks/fix_collection_labels.rake
Connected to https://github.com/emory-libraries/dlp-curate/issues/470
=> Fix missing translations for collection labels

app/forms/hyrax/forms/collection_form.rb, spec/forms/hyrax/forms/collection_form_spec.rb
The `visibility` property needs to be present in the `Form`
class.
=> Fix for Collection visibility not saving

app/importers/curate_mapper.rb, spec/importers/curate_mapper_spec.rb
Connected to https://github.com/curationexperts/in-house/issues/213
=> Required csv fields

app/importers/curate_mapper.rb, spec/importers/curate_mapper_spec.rb
Connected to https://github.com/curationexperts/in-house/issues/214
=> Add legacy_identifier and abstract to importer

app/importers/curate_mapper.rb, spec/importers/curate_mapper_spec.rb
Connected to https://github.com/curationexperts/in-house/issues/214
=> Adding more plain text strings to metadata mapping

app/views/metadata_details/show.html.erb
Tiny fix-up after DCE team discussion at standup.
=> Clarify field labels

app/importers/curate_mapper.rb, spec/importers/curate_mapper_spec.rb
Connected to https://github.com/curationexperts/in-house/issues/221
=> Use controlled vocab for sensitive_material field

app/forms/hyrax/curate_generic_work_form.rb, app/lib/metadata_details.rb, app/views/metadata_details/show.html.erb, config/initializers/required_fields_on_form.rb
This adds the required field on form property to
the guide and csv.
=> Add whether a field is required on the form to guide

app/uploaders/zizia/csv_manifest_validator.rb, spec/uploaders/zizia/csv_manifest_validator_spec.rb
Raise a warning if there are too many or too few rows for each line in
the CSV
Connected to https://github.com/curationexperts/in-house/issues/252
=> Check for number of fields in all rows

app/uploaders/zizia/csv_manifest_validator.rb, spec/uploaders/zizia/csv_manifest_validator_spec.rb
Connected to https://github.com/curationexperts/in-house/issues/258
=> Check for valid sensitive_material values

app/models/curate_generic_work.rb, spec/factories/curate_generic_works.rb, spec/system/viewing_a_work_spec.rb
Connected to curationexperts/in-house#255
=> Index the extent attribute in Solr

app/models/curate_generic_work.rb, spec/factories/curate_generic_works.rb, spec/system/viewing_a_work_spec.rb
Connected to curationexperts/in-house#256
=> Index the rights statement text attribute in Solr

app/importers/curate_record_importer.rb, spec/system/langmuir_file_attachment_spec.rb
Connected to https://github.com/curationexperts/in-house/issues/268
=> The :pcdm_use for any imported fileset is FileSet::PRIMARY

config/authorities/resource_types.yml, spec/services/hyrax/resource_types_service_spec.rb
=> Add artifact to resource types

lib/user_setup.rb, spec/lib/user_setup_spec.rb
=> Improves adding users to user-groups

.rubocop.yml, app/importers/modular_importer.rb, app/importers/modular_importer_details_decorator.rb, app/importers/modular_importer_logging_decorator.rb, app/jobs/zizia/start_csv_import_job.rb, config/initializers/prepends.rb, config/prepends/hyrax_record_importer_prepends.rb, spec/system/import_langmuir_from_csv_spec.rb, spec/system/importer_preprocessed_langmuir_spec.rb
This adds two modules which are used to add
logging and recording of the csv import details based
on the current status of the import.
=> Basic logging and details recording

app/importers/modular_importer.rb, spec/system/import_langmuir_from_csv_spec.rb
This adds imported works to the selected collection.
=> Add collection membership

.rubocop.yml, app/models/file_set.rb, app/models/preservation_event.rb, app/models/preservation_uri.rb, app/models/preservation_workflow.rb, spec/models/file_set_spec.rb
=> Adds preservation_event to file_set model

.rubocop.yml, app/controllers/hyrax/file_sets_controller.rb, app/views/hyrax/file_sets/media_display/_image.html.erb, app/views/hyrax/file_sets/media_display/_office_document.html.erb , app/views/hyrax/file_sets/media_display/_pdf.html.erb 
=> displays correct images

.rubocop.yml, app/actors/hyrax/actors/file_set_actor.rb, app/jobs/create_work_job.rb, app/lib/preservation_events.rb, spec/actors/hyrax/actors/file_set_actor_spec.rb, spec/jobs/create_work_job_spec.rb
Also, edits preservation_event for fileset creation
=> Adds preservation_event for work creation

Gemfile, Gemfile.lock, app/models/ability.rb, spec/system/import_langmuir_from_csv_spec.rb
Connected to https://github.com/curationexperts/in-house/issues/399
=> Upgrade to zizia 5.0.1

.rubocop.yml, app/actors/hyrax/actors/file_set_actor.rb, app/jobs/create_work_job.rb, app/lib/preservation_events.rb
=> Updates preservation_event log creation

app/importers/yellowback_preprocessor.rb, spec/fixtures/csv_import/yellowbacks/yellowbacks_marc.xml, spec/importers/yellowback_preprocessor_spec.rb
Add fields extracted from an Alma MARCxml input file to fields already extracted from the pull list CSV.
=> Add Alma mappings to Yellowback preprocessor

Gemfile, Gemfile.lock
This version includes status UI for imported
works on the 'Works and Files' page.
=> Update Zizia to version 5.4.0

.rubocop.yml, app/jobs/characterize_job.rb, spec/jobs/characterize_job_spec.rb
* This commit adds the relation and filename to the event_details when
creating a characterization event
=> Edits event_details for characterization event

architecture-decisions/0000-TEMPLATE.md, architecture-decisions/0001-document-architecture-decisions.md
=> Adds ADRs for this application

config/initializers/job_io_wrapper.rb, spec/models/job_io_wrapper_spec.rb
This commit revises event_details for the file-submission
preservation event, as per requirements.
=> Revises eventDetails text for file-submission

app/models/file_set.rb
This commit adds clamav software version to the virus check
preservation event
=> Adds clamav version to virus preservation_event

architecture-decisions/0002-S3-Versioning.md
Versioning is causing problems, and may be holding back Cantaloupe.
=> Decides if we replace versioning with batch operations in S3

app/indexers/curate_generic_work_indexer.rb, app/models/solr_document.rb, spec/models/curate_generic_work_spec.rb, spec/models/job_io_wrapper_spec.rb
Hopefully resolves any edit conflicts resulting from CI queue 
Connected to: https://github.com/emory-libraries/dlp-lux/issues/62
=> Add human readable content_type

app/importers/langmuir_preprocessor.rb, app/importers/yellowback_preprocessor.rb
Add a progress bar to the Langmuir and Kirtas pre-processors
Re-submitting these commits from @mark-dce because the PR got stale.
=> Progress bar redux

config/sidekiq.yml
Adjustments to the sidekiq config to avoid using the SIDEKIQ_WORKERS variable which was not being recognized.
=> Hard code sidekiq workers

config/deploy/arch.rb, config/deploy/production.rb, config/deploy/test.rb, config/honeybadger.yml
Env is consistent for deploys and errors, too.
=> Sets Honeybadger Env, and turns on breadcrumbs

spec/system/iiif_manifest_spec.rb
Tests specific contents of IIIF manifest creation
=> IIIF Manifest test

.rubocop.yml, app/indexers/curate_generic_work_indexer.rb, spec/models/visibility_spec.rb
Index two fields for access facet for Lux.
=> Access facet for lux

app/controllers/iiif_controller.rb, spec/controllers/iiif_controller_spec.rb
When a work has a visibility value of low_res, force its iiif queries to
request a size no larger than the MAX_PIXELS_FOR_LOW_RES value. Default
value is 400 pixels.
Connected to https://github.com/emory-libraries/dlp-lux/issues/313
=> Force public low view objects to low resolution

app/controllers/iiif_controller.rb, spec/controllers/iiif_controller_spec.rb
=> More flexible iiif rewrites

architecture-decisions/0004-IIIF-Manifest-Caching.md
Although most of this work is done, this documents the motivation for IIIF manifest caching.
=> ADR for IIIF Manifest Caching

app/assets/stylesheets/curate.scss, app/forms/hyrax/forms/collection_form.rb, app/views/hyrax/dashboard/collections/_form.html.erb, spec/system/edit_collection_spec.rb
=> adds functionality to pick a collection thumbnail

.rubocop.yml, app/indexers/curate_collection_indexer.rb, app/jobs/characterize_job.rb, app/models/concerns/hyrax/collection_behavior.rb, app/presenters/hyrax/collection_presenter.rb, spec/jobs/characterize_job_spec.rb, spec/models/collection_spec.rb
Closes #1074
This is a collection size removal implementation based on these 2 commits:
https://github.com/samvera/hyrax/pull/4207/commits
=> removes collection size feature

config/locales/en.yml, config/locales/hyrax.en.yml
=> fixes the heading collection filter label

app/assets/javascripts/hyrax/file_manager/sorting.es6
=> implements natural sort of alphanumerical strings

app/assets/javascripts/hyrax/thumbnail_select.es6
=> adds free text option to thumbnail select2

app/views/hyrax/file_sets/show.html.erb, spec/system/show_file_spec.rb
* This commit changes the use for creating download link for extracted text file in a file_set.
=> Changes url params for extracted text download

app/views/hyrax/file_sets/show.html.erb, spec/system/show_file_spec.rb
- Adds fileset ID to fileset show page
- Adjusts display of fileset category and parent work on fileset show page
=> Add fileset ID to fileset show page

.rubocop.yml, Gemfile, Gemfile.lock, app/actors/hyrax/actors/file_set_actor.rb, app/builders/curate_manifest_helper.rb, app/controllers/iiif_controller.rb, app/forms/hyrax/forms/collection_form.rb, app/importers/curate_mapper.rb, app/importers/curate_record_importer.rb, app/importers/modular_importer_update_decorator.rb, app/importers/preservation_workflow_importer.rb, app/indexers/curate_generic_work_indexer.rb, app/jobs/attach_files_to_work_job.rb, app/lib/metadata_details.rb, app/models/curate_generic_work.rb, app/models/file_set.rb, app/models/hyrax/uploaded_file.rb, app/presenters/hyrax/collection_presenter.rb, app/presenters/hyrax/curate_generic_work_presenter.rb, app/uploaders/zizia/csv_manifest_validator.rb, spec/forms/hyrax/curate_generic_work_form_spec.rb, spec/importers/preservation_workflow_importer_spec.rb, spec/jobs/attach_files_to_work_job_spec.rb, spec/lib/curate_generic_work_attributes_spec.rb, spec/models/curate/curate_collection_type_spec.rb, spec/models/file_set_spec.rb, spec/models/hyrax/collection_type_spec.rb, spec/system/iiif_access_controls_spec.rb, spec/system/show_file_spec.rb
Capybara also needed to be upgraded. Bixby was upgraded to a commit rather than a version to allow us to us Rails style private methods.
=> Updates Bixby and resolves the conflicts

app/controllers/hyrax/dashboard/collections_controller_override.rb, app/controllers/hyrax/downloads_controller.rb, app/controllers/hyrax/file_sets_controller.rb
=> upgrades controllers to beta 3

app/controllers/hyrax/file_sets_controller.rb, spec/controllers/hyrax/downloads_controller_spec.rb, spec/controllers/hyrax/file_sets_controller_spec.rb, spec/controllers/iiif_controller_spec.rb
* Updates required controller specs to make the suite greener.
=> Controller spec update

spec/services/parent_query_service_spec.rb
* spec/services/parent_query_service_spec.rb: Updates `SolrService` parent module to `Hyrax`.
=> Updates services spec

spec/requests/iiif_requests_spec.rb
* spec/requests/iiif_requests_spec.rb: Changes `User-Agent` to new version.
=> Updates requests specs

spec/forms/hyrax/forms/collection_form_spec.rb
* spec/forms/hyrax/forms/collection_form_spec.rb: changes alt_title field to an array/makes it multi valued.
=> Updates forms spec

app/forms/hyrax/curate_generic_work_form.rb
=> Revises placement of dedup-key in work form

app/views/preservation_events/_preservation_events.html.erb, spec/system/show_file_spec.rb
=> Display fileset events in reverse chronological order

app/jobs/collection_files_ingested_job.rb, lib/tasks/collection_files_ingested.rake, spec/jobs/collection_files_ingested_job_spec.rb
- app/jobs/collection_files_ingested_job.rb: pulls and writes file stats to a json file.
- lib/tasks/collection_files_ingested.rake: creates rake task to process the above job.
- spec/*: ensures above job works correctly.
=> Exports Collection file statistics to a json file (#1252).

app/views/_controls.html.erb, spec/system/viewing_homepage_spec.rb
- app/views/_controls.html.erb: brought in to override hyrax' link.
- spec/system/viewing_homepage_spec.rb: creates test to make sure link goes to the right destination.
=> Changes contact link to libwizard service (#1345).

Gemfile.lock, spec/system/create_curate_generic_work_spec.rb
Reverts emory-libraries/dlp-curate#1409, and updates the QA gem to avoid the failure.
=> Revert "Skips failing QA test"

lib/tasks/README.md, lib/tasks/curate_books.rake, lib/tasks/curate_langmuir.rake
- lib/tasks/README.md: creates Readme within same folder as Rake Tasks.
- lib/tasks/curate_langmuir.rake and lib/tasks/curate_books.rake: corrects some verbiage and a command.
=> Adds Rake Tasks README and corrects some verbiage in other tasks (#1368).

spec/controllers/background_jobs_controller_spec.rb
**`spec/controllers/background_jobs_controller_spec.rb`**
1. L# 7, 19-23: have to clear jobs after each test since Jobs were still in queue when next test started, throwing errors.
2. L# 37, 42: csv files were being called in the wrong posts--swapped them out.
3. L# 44: to avoid errors, we need to call out how many times the job will be enqueued.
=> Corrects errors found when troubleshooting the BackgroundJobsController spec.

app/controllers/background_jobs_controller.rb
=> pulls path from the environment or tmp folder

app/actors/hyrax/actors/curate_generic_work_actor.rb, spec/actors/hyrax/actors/curate_generic_work_actor_spec.rb
- Added an update method to generic curate work actor 
- In the update method,  added a generic modification preservation event if the update is successful
- Added a test for the update method in curate generic work actor
=> creates a generic modification event on work update

Capfile, Gemfile, Gemfile.lock, config/schedule.rb
* We are adding the whenever gem in order to schedule the running of the fixity check rake task through a cron job on the 3rd of every 3rd month.
=> Adds whenever gem so that we can use server's cron abilities

app/presenters/hyrax/curate_generic_work_presenter.rb, spec/system/viewing_a_work_spec.rb
- app/presenters/hyrax/curate_generic_work_presenter.rb: overrides a method that renders the visibility badge.
- spec/system/viewing_a_work_spec.rb: tests expectations for the visibility badge.
=> Fix visibility badge display 1502

app/views/hyrax/users/_vitals.html.erb, spec/system/viewing_a_user_spec.rb
- app/views/hyrax/users/_vitals.html.erb: brings in override so that links can be corrected.
- spec/system/viewing_a_user_spec.rb: tests the link corrections.
=> Fixes the Collections and Works created links on the User show page (#673).

app/views/_controls.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/hyrax/base/_form.html.erb, app/views/hyrax/base/_form_visibility_component.html.erb, app/views/hyrax/base/_show_actions.html.erb, app/views/hyrax/collections/_show_descriptions.html.erb, app/views/hyrax/collections/show.html.erb, app/views/hyrax/dashboard/collections/_form.html.erb, app/views/hyrax/dashboard/collections/_form_branding.html.erb, app/views/hyrax/dashboard/collections/_show_descriptions.html.erb
- All files: update versions in overwrite verbiage.
- app/views/_controls.html.erb: adds aria label.
- app/views/catalog/_index_list_default.html.erb: inserts data-solr-field-name attribute to field.
- app/views/hyrax/base/_form.html.erb: passes tab argument in method call.
- app/views/hyrax/base/_form_visibility_component.html.erb: changes tests validators to new helpers.
- app/views/hyrax/base/_show_actions.html.erb: updates calls and inserts validations found in new version.
- app/views/hyrax/collections/_show_descriptions.html.erb: refactors method calls and classes based on new code.
- app/views/hyrax/collections/show.html.erb: swaps out element classifications and generally reworks calls based on new code.
- app/views/hyrax/dashboard/collections/_form.html.erb: uses test helper …
=> Brad's Views Work.

app/services/hyrax/file_set_fixity_check_service.rb
app/services/hyrax/file_set_fixity_check_service.rb: updates verbiage (all Rspec passed).
=> Brad's Services Work (#1675).

app/search_builders/hyrax/collection_member_search_builder.rb
app/search_builders/hyrax/collection_member_search_builder.rb: brings over new methods to the class from v3.1.0.
=> Brad's SearchBuilder work (#1674).

app/actors/hyrax/actors/file_set_actor.rb
* Work in the new hyrax version is related to valkyrie and wings which we do not intend to use.
* We have modified the file_set_actor to meet DLP requirements.
* We might want to look at moving work-fileset associationcreation to its original place in the file_set_actor and taking it out from the attach_files_to_work_job, if the slow fileset attach rates continue.
=> Updates file_set_actor to match new hyrax version

app/models/aws_fixity_event.rb, spec/models/aws_fixity_event_spec.rb
All: updates all files with the expected outcome strings coming from Beth's scripts.
Backend only, no screenshots necessary.
=> Changes the expected outcome text.

app/controllers/hyrax/file_sets_controller.rb
=> Remove access to public file sets without authentication

app/controllers/hyrax/file_sets_controller.rb, spec/controllers/hyrax/file_sets_controller_spec.rb
Issue #1804 
PR #1815 did not pass two specific tests for access to private and public file sets. This PR fixes those specs to reflect the new changes regarding denying access to public file sets without authentication.
=> Fix tests for access to private and public file sets

.circleci/config.yml
.circleci/config.yml: Imports commit from my Ruby 2.5 branch to main.
=> Brings pub key fix to main.

app/models/curate/collection_type.rb, app/views/hyrax/base/_form.html.erb, app/views/hyrax/dashboard/collections/show.html.erb
Ticket: #1921
Resolve spec failures from the following files:
* `spec/system/migration_collections_spec.rb`
* `spec/system/fileset_uploader_spec.rb`
=> Resolve spec failures

app/controllers/hyrax/file_sets_controller.rb, app/views/hyrax/file_sets/show.html.erb
Address the following issue reported by Code Climate:
=> Resolve code climate issues

app/models/hyrax/uploaded_file.rb, spec/models/hyrax/uploaded_file_spec.rb
- Add better test coverage for model `uploaded_file.rb`
=> Add uploaded_file_spec.rb

app/jobs/compile_full_text_job.rb, spec/fixtures/full_text_data/page_1_transcript.txt, spec/fixtures/full_text_data/page_2_transcript.txt, spec/jobs/compile_full_text_job_spec.rb
Implements #2028
In this PR, I add a new Sidekiq worker that compiles full text data from all all the file sets labeled "Page ..." and adds a new file set that contains a transcript file with all that data.
=> Add sidekiq worker compile full text

app/indexers/curate_generic_work_indexer.rb, app/jobs/compile_full_text_job.rb, app/models/curate_generic_work.rb, spec/indexers/curate_generic_work_indexer_spec.rb, spec/jobs/compile_full_text_job_spec.rb
=> Add indexing full text data to work indexing

app/views/bulkrax/shared/_collection_entries_tab.html.erb, app/views/bulkrax/shared/_file_set_entries_tab.html.erb, app/views/bulkrax/shared/_work_entries_tab.html.erb, spec/system/bulkrax_csv_export_spec.rb
- app/views/bulkrax/shared/*: inserts the new Title column to each object's list table.
- spec/*: tests for the presence of those columns.
=> Adds Title to all object entry tables (#2017).

app/views/layouts/application.html.erb
=> Adds the Google Tag tracking script to Curate (#2094).

app/controllers/aspace_controller.rb, spec/controllers/aspace_controller_spec.rb
Replace param `resource_id` with `call_number` to improve readability
=> Refactor aspace controller

.rubocop.yml, app/services/aspace/api_service.rb, app/services/aspace/reports_service.rb, lib/tasks/compile_aspace_resources.rake, spec/fixtures/archivesspace_api/resources_by_page.json, spec/services/aspace/reports_service_spec.rb
Implements https://github.com/emory-libraries/aspace/issues/26
=> Add ArchivesSpace resources report task

app/services/aspace/api_service.rb, app/services/aspace/formatting_service.rb, app/views/hyrax/dashboard/collections/new.html.erb, spec/controllers/aspace_controller_spec.rb, spec/services/aspace/api_service_spec.rb, spec/services/aspace/formatting_service_spec.rb
Ticket https://github.com/emory-libraries/aspace/issues/113
- Autopopulate `finding_aid_link`
- Autopopulate `system_of_record_id`
=> Edit Aspace resource formatting

app/services/aspace/formatting_service.rb, spec/services/aspace/api_service_spec.rb, spec/services/aspace/formatting_service_spec.rb
Ticket [#127](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/127)
=> Edit Aspace formatting service

app/indexers/curate/file_set_indexer.rb
=> Adds image height and width to Curate::TextExtraction::AltoReader for scaling.

Gemfile, Gemfile.lock, README.md, config/deploy/arch.rb, config/deploy/production.rb, config/deploy/test.rb
- Gemfile*: installs new gem that handles ip lookup.
- README.md: details the new instructions for deployment.
- config/deploy/*: utilizes the new gem processing to get the servers' private IP addresses.
=> Uses new EC2 lookup gem for automated IP pulling.
